# THIS IS AI GENERATED CODE
FROM openapitools/openapi-generator-cli:v7.12.0

WORKDIR /out

ENTRYPOINT ["docker-entrypoint.sh", "generate", \
    "-g", "go", \
    "--package-name", "embyclient", \
    "--skip-validate-spec", \
    "--additional-properties", "generateInterfaces=true,enumClassPrefix=true", \
    "-o", "/out" \
]
