/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type SubtitleServiceAPI interface {

	/*
	DeleteItemsByIdSubtitlesByIndex Deletes an external subtitle file

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param index The subtitle stream index
	@return ApiDeleteItemsByIdSubtitlesByIndexRequest
	*/
	DeleteItemsByIdSubtitlesByIndex(ctx context.Context, id string, index int32) ApiDeleteItemsByIdSubtitlesByIndexRequest

	// DeleteItemsByIdSubtitlesByIndexExecute executes the request
	DeleteItemsByIdSubtitlesByIndexExecute(r ApiDeleteItemsByIdSubtitlesByIndexRequest) (*http.Response, error)

	/*
	DeleteVideosByIdSubtitlesByIndex Deletes an external subtitle file

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param index The subtitle stream index
	@return ApiDeleteVideosByIdSubtitlesByIndexRequest
	*/
	DeleteVideosByIdSubtitlesByIndex(ctx context.Context, id string, index int32) ApiDeleteVideosByIdSubtitlesByIndexRequest

	// DeleteVideosByIdSubtitlesByIndexExecute executes the request
	DeleteVideosByIdSubtitlesByIndexExecute(r ApiDeleteVideosByIdSubtitlesByIndexRequest) (*http.Response, error)

	/*
	GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@param startPositionTicks StartPositionTicks
	@return ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
	*/
	GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest

	// GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute executes the request
	GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error)

	/*
	GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@return ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
	*/
	GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest

	// GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute executes the request
	GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error)

	/*
	GetItemsByIdRemotesearchSubtitlesByLanguage Method for GetItemsByIdRemotesearchSubtitlesByLanguage

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param language Language
	@return ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest
	*/
	GetItemsByIdRemotesearchSubtitlesByLanguage(ctx context.Context, id string, language string) ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest

	// GetItemsByIdRemotesearchSubtitlesByLanguageExecute executes the request
	//  @return []RemoteSubtitleInfo
	GetItemsByIdRemotesearchSubtitlesByLanguageExecute(r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) ([]RemoteSubtitleInfo, *http.Response, error)

	/*
	GetProvidersSubtitlesSubtitlesById Method for GetProvidersSubtitlesSubtitlesById

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@return ApiGetProvidersSubtitlesSubtitlesByIdRequest
	*/
	GetProvidersSubtitlesSubtitlesById(ctx context.Context, id string) ApiGetProvidersSubtitlesSubtitlesByIdRequest

	// GetProvidersSubtitlesSubtitlesByIdExecute executes the request
	GetProvidersSubtitlesSubtitlesByIdExecute(r ApiGetProvidersSubtitlesSubtitlesByIdRequest) (*http.Response, error)

	/*
	GetVideosByIdByMediasourceidAttachmentsByIndexStream Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@return ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest
	*/
	GetVideosByIdByMediasourceidAttachmentsByIndexStream(ctx context.Context, id string, mediaSourceId string, index int32) ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest

	// GetVideosByIdByMediasourceidAttachmentsByIndexStreamExecute executes the request
	GetVideosByIdByMediasourceidAttachmentsByIndexStreamExecute(r ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest) (*http.Response, error)

	/*
	GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@param startPositionTicks StartPositionTicks
	@return ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
	*/
	GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest

	// GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute executes the request
	GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error)

	/*
	GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@return ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
	*/
	GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest

	// GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute executes the request
	GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error)

	/*
	HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@param startPositionTicks StartPositionTicks
	@return ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
	*/
	HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest

	// HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute executes the request
	HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error)

	/*
	HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@return ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
	*/
	HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest

	// HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute executes the request
	HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error)

	/*
	HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@param startPositionTicks StartPositionTicks
	@return ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
	*/
	HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest

	// HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute executes the request
	HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error)

	/*
	HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param mediaSourceId MediaSourceId
	@param index The subtitle stream index
	@param format Format
	@return ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
	*/
	HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest

	// HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute executes the request
	HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error)

	/*
	PostItemsByIdRemotesearchSubtitlesBySubtitleid Method for PostItemsByIdRemotesearchSubtitlesBySubtitleid

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param subtitleId SubtitleId
	@return ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest
	*/
	PostItemsByIdRemotesearchSubtitlesBySubtitleid(ctx context.Context, id string, subtitleId string) ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest

	// PostItemsByIdRemotesearchSubtitlesBySubtitleidExecute executes the request
	//  @return SubtitlesSubtitleDownloadResult
	PostItemsByIdRemotesearchSubtitlesBySubtitleidExecute(r ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest) (*SubtitlesSubtitleDownloadResult, *http.Response, error)

	/*
	PostItemsByIdSubtitlesByIndexDelete Deletes an external subtitle file

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param index The subtitle stream index
	@return ApiPostItemsByIdSubtitlesByIndexDeleteRequest
	*/
	PostItemsByIdSubtitlesByIndexDelete(ctx context.Context, id string, index int32) ApiPostItemsByIdSubtitlesByIndexDeleteRequest

	// PostItemsByIdSubtitlesByIndexDeleteExecute executes the request
	PostItemsByIdSubtitlesByIndexDeleteExecute(r ApiPostItemsByIdSubtitlesByIndexDeleteRequest) (*http.Response, error)

	/*
	PostVideosByIdSubtitlesByIndexDelete Deletes an external subtitle file

	Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param index The subtitle stream index
	@return ApiPostVideosByIdSubtitlesByIndexDeleteRequest
	*/
	PostVideosByIdSubtitlesByIndexDelete(ctx context.Context, id string, index int32) ApiPostVideosByIdSubtitlesByIndexDeleteRequest

	// PostVideosByIdSubtitlesByIndexDeleteExecute executes the request
	PostVideosByIdSubtitlesByIndexDeleteExecute(r ApiPostVideosByIdSubtitlesByIndexDeleteRequest) (*http.Response, error)
}

// SubtitleServiceAPIService SubtitleServiceAPI service
type SubtitleServiceAPIService service

type ApiDeleteItemsByIdSubtitlesByIndexRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId *string
	index int32
}

// MediaSourceId
func (r ApiDeleteItemsByIdSubtitlesByIndexRequest) MediaSourceId(mediaSourceId string) ApiDeleteItemsByIdSubtitlesByIndexRequest {
	r.mediaSourceId = &mediaSourceId
	return r
}

func (r ApiDeleteItemsByIdSubtitlesByIndexRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteItemsByIdSubtitlesByIndexExecute(r)
}

/*
DeleteItemsByIdSubtitlesByIndex Deletes an external subtitle file

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param index The subtitle stream index
 @return ApiDeleteItemsByIdSubtitlesByIndexRequest
*/
func (a *SubtitleServiceAPIService) DeleteItemsByIdSubtitlesByIndex(ctx context.Context, id string, index int32) ApiDeleteItemsByIdSubtitlesByIndexRequest {
	return ApiDeleteItemsByIdSubtitlesByIndexRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		index: index,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) DeleteItemsByIdSubtitlesByIndexExecute(r ApiDeleteItemsByIdSubtitlesByIndexRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.DeleteItemsByIdSubtitlesByIndex")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/Subtitles/{Index}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mediaSourceId == nil {
		return nil, reportError("mediaSourceId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "MediaSourceId", r.mediaSourceId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDeleteVideosByIdSubtitlesByIndexRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId *string
	index int32
}

// MediaSourceId
func (r ApiDeleteVideosByIdSubtitlesByIndexRequest) MediaSourceId(mediaSourceId string) ApiDeleteVideosByIdSubtitlesByIndexRequest {
	r.mediaSourceId = &mediaSourceId
	return r
}

func (r ApiDeleteVideosByIdSubtitlesByIndexRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteVideosByIdSubtitlesByIndexExecute(r)
}

/*
DeleteVideosByIdSubtitlesByIndex Deletes an external subtitle file

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param index The subtitle stream index
 @return ApiDeleteVideosByIdSubtitlesByIndexRequest
*/
func (a *SubtitleServiceAPIService) DeleteVideosByIdSubtitlesByIndex(ctx context.Context, id string, index int32) ApiDeleteVideosByIdSubtitlesByIndexRequest {
	return ApiDeleteVideosByIdSubtitlesByIndexRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		index: index,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) DeleteVideosByIdSubtitlesByIndexExecute(r ApiDeleteVideosByIdSubtitlesByIndexRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.DeleteVideosByIdSubtitlesByIndex")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/Subtitles/{Index}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mediaSourceId == nil {
		return nil, reportError("mediaSourceId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "MediaSourceId", r.mediaSourceId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// EndPositionTicks
func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r)
}

/*
GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @param startPositionTicks StartPositionTicks
 @return ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	return ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
		startPositionTicks: startPositionTicks,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiGetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/{MediaSourceId}/Subtitles/{Index}/{StartPositionTicks}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"StartPositionTicks"+"}", url.PathEscape(parameterValueToString(r.startPositionTicks, "startPositionTicks")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks *int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// StartPositionTicks
func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) StartPositionTicks(startPositionTicks int64) ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.startPositionTicks = &startPositionTicks
	return r
}

// EndPositionTicks
func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r)
}

/*
GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @return ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	return ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiGetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/{MediaSourceId}/Subtitles/{Index}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.startPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartPositionTicks", r.startPositionTicks, "form", "")
	}
	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId *string
	language string
	isPerfectMatch *bool
	isForced *bool
	isHearingImpaired *bool
}

// MediaSourceId
func (r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) MediaSourceId(mediaSourceId string) ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest {
	r.mediaSourceId = &mediaSourceId
	return r
}

// IsPerfectMatch
func (r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) IsPerfectMatch(isPerfectMatch bool) ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest {
	r.isPerfectMatch = &isPerfectMatch
	return r
}

// IsForced
func (r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) IsForced(isForced bool) ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest {
	r.isForced = &isForced
	return r
}

// IsHearingImpaired
func (r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) IsHearingImpaired(isHearingImpaired bool) ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest {
	r.isHearingImpaired = &isHearingImpaired
	return r
}

func (r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) Execute() ([]RemoteSubtitleInfo, *http.Response, error) {
	return r.ApiService.GetItemsByIdRemotesearchSubtitlesByLanguageExecute(r)
}

/*
GetItemsByIdRemotesearchSubtitlesByLanguage Method for GetItemsByIdRemotesearchSubtitlesByLanguage

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param language Language
 @return ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest
*/
func (a *SubtitleServiceAPIService) GetItemsByIdRemotesearchSubtitlesByLanguage(ctx context.Context, id string, language string) ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest {
	return ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		language: language,
	}
}

// Execute executes the request
//  @return []RemoteSubtitleInfo
func (a *SubtitleServiceAPIService) GetItemsByIdRemotesearchSubtitlesByLanguageExecute(r ApiGetItemsByIdRemotesearchSubtitlesByLanguageRequest) ([]RemoteSubtitleInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []RemoteSubtitleInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetItemsByIdRemotesearchSubtitlesByLanguage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/RemoteSearch/Subtitles/{Language}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Language"+"}", url.PathEscape(parameterValueToString(r.language, "language")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mediaSourceId == nil {
		return localVarReturnValue, nil, reportError("mediaSourceId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "MediaSourceId", r.mediaSourceId, "form", "")
	if r.isPerfectMatch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "IsPerfectMatch", r.isPerfectMatch, "form", "")
	}
	if r.isForced != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "IsForced", r.isForced, "form", "")
	}
	if r.isHearingImpaired != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "IsHearingImpaired", r.isHearingImpaired, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetProvidersSubtitlesSubtitlesByIdRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
}

func (r ApiGetProvidersSubtitlesSubtitlesByIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetProvidersSubtitlesSubtitlesByIdExecute(r)
}

/*
GetProvidersSubtitlesSubtitlesById Method for GetProvidersSubtitlesSubtitlesById

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @return ApiGetProvidersSubtitlesSubtitlesByIdRequest
*/
func (a *SubtitleServiceAPIService) GetProvidersSubtitlesSubtitlesById(ctx context.Context, id string) ApiGetProvidersSubtitlesSubtitlesByIdRequest {
	return ApiGetProvidersSubtitlesSubtitlesByIdRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) GetProvidersSubtitlesSubtitlesByIdExecute(r ApiGetProvidersSubtitlesSubtitlesByIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetProvidersSubtitlesSubtitlesById")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Providers/Subtitles/Subtitles/{Id}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
}

func (r ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetVideosByIdByMediasourceidAttachmentsByIndexStreamExecute(r)
}

/*
GetVideosByIdByMediasourceidAttachmentsByIndexStream Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @return ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest
*/
func (a *SubtitleServiceAPIService) GetVideosByIdByMediasourceidAttachmentsByIndexStream(ctx context.Context, id string, mediaSourceId string, index int32) ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest {
	return ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) GetVideosByIdByMediasourceidAttachmentsByIndexStreamExecute(r ApiGetVideosByIdByMediasourceidAttachmentsByIndexStreamRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetVideosByIdByMediasourceidAttachmentsByIndexStream")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{MediaSourceId}/Attachments/{Index}/Stream"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// EndPositionTicks
func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r)
}

/*
GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @param startPositionTicks StartPositionTicks
 @return ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	return ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
		startPositionTicks: startPositionTicks,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiGetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{MediaSourceId}/Subtitles/{Index}/{StartPositionTicks}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"StartPositionTicks"+"}", url.PathEscape(parameterValueToString(r.startPositionTicks, "startPositionTicks")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks *int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// StartPositionTicks
func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) StartPositionTicks(startPositionTicks int64) ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.startPositionTicks = &startPositionTicks
	return r
}

// EndPositionTicks
func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r)
}

/*
GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @return ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	return ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiGetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.GetVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{MediaSourceId}/Subtitles/{Index}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.startPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartPositionTicks", r.startPositionTicks, "form", "")
	}
	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// EndPositionTicks
func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r)
}

/*
HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @param startPositionTicks StartPositionTicks
 @return ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	return ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
		startPositionTicks: startPositionTicks,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodHead
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.HeadItemsByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/{MediaSourceId}/Subtitles/{Index}/{StartPositionTicks}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"StartPositionTicks"+"}", url.PathEscape(parameterValueToString(r.startPositionTicks, "startPositionTicks")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks *int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// StartPositionTicks
func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) StartPositionTicks(startPositionTicks int64) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.startPositionTicks = &startPositionTicks
	return r
}

// EndPositionTicks
func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r)
}

/*
HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @return ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	return ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiHeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodHead
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.HeadItemsByIdByMediasourceidSubtitlesByIndexStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/{MediaSourceId}/Subtitles/{Index}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.startPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartPositionTicks", r.startPositionTicks, "form", "")
	}
	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// EndPositionTicks
func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r)
}

/*
HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @param startPositionTicks StartPositionTicks
 @return ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string, startPositionTicks int64) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest {
	return ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
		startPositionTicks: startPositionTicks,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatExecute(r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodHead
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.HeadVideosByIdByMediasourceidSubtitlesByIndexByStartpositionticksStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{MediaSourceId}/Subtitles/{Index}/{StartPositionTicks}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"StartPositionTicks"+"}", url.PathEscape(parameterValueToString(r.startPositionTicks, "startPositionTicks")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId string
	index int32
	format string
	startPositionTicks *int64
	endPositionTicks *int64
	copyTimestamps *bool
}

// StartPositionTicks
func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) StartPositionTicks(startPositionTicks int64) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.startPositionTicks = &startPositionTicks
	return r
}

// EndPositionTicks
func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) EndPositionTicks(endPositionTicks int64) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.endPositionTicks = &endPositionTicks
	return r
}

// CopyTimestamps
func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) CopyTimestamps(copyTimestamps bool) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

func (r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r)
}

/*
HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat Gets subtitles in a specified format.

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param mediaSourceId MediaSourceId
 @param index The subtitle stream index
 @param format Format
 @return ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest
*/
func (a *SubtitleServiceAPIService) HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int32, format string) ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest {
	return ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		mediaSourceId: mediaSourceId,
		index: index,
		format: format,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatExecute(r ApiHeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormatRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodHead
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.HeadVideosByIdByMediasourceidSubtitlesByIndexStreamByFormat")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{MediaSourceId}/Subtitles/{Index}/Stream.{Format}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"MediaSourceId"+"}", url.PathEscape(parameterValueToString(r.mediaSourceId, "mediaSourceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Format"+"}", url.PathEscape(parameterValueToString(r.format, "format")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.startPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartPositionTicks", r.startPositionTicks, "form", "")
	}
	if r.endPositionTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EndPositionTicks", r.endPositionTicks, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId *string
	subtitleId string
}

// MediaSourceId
func (r ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest) MediaSourceId(mediaSourceId string) ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest {
	r.mediaSourceId = &mediaSourceId
	return r
}

func (r ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest) Execute() (*SubtitlesSubtitleDownloadResult, *http.Response, error) {
	return r.ApiService.PostItemsByIdRemotesearchSubtitlesBySubtitleidExecute(r)
}

/*
PostItemsByIdRemotesearchSubtitlesBySubtitleid Method for PostItemsByIdRemotesearchSubtitlesBySubtitleid

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param subtitleId SubtitleId
 @return ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest
*/
func (a *SubtitleServiceAPIService) PostItemsByIdRemotesearchSubtitlesBySubtitleid(ctx context.Context, id string, subtitleId string) ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest {
	return ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		subtitleId: subtitleId,
	}
}

// Execute executes the request
//  @return SubtitlesSubtitleDownloadResult
func (a *SubtitleServiceAPIService) PostItemsByIdRemotesearchSubtitlesBySubtitleidExecute(r ApiPostItemsByIdRemotesearchSubtitlesBySubtitleidRequest) (*SubtitlesSubtitleDownloadResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SubtitlesSubtitleDownloadResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.PostItemsByIdRemotesearchSubtitlesBySubtitleid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/RemoteSearch/Subtitles/{SubtitleId}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"SubtitleId"+"}", url.PathEscape(parameterValueToString(r.subtitleId, "subtitleId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mediaSourceId == nil {
		return localVarReturnValue, nil, reportError("mediaSourceId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "MediaSourceId", r.mediaSourceId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostItemsByIdSubtitlesByIndexDeleteRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId *string
	index int32
}

// MediaSourceId
func (r ApiPostItemsByIdSubtitlesByIndexDeleteRequest) MediaSourceId(mediaSourceId string) ApiPostItemsByIdSubtitlesByIndexDeleteRequest {
	r.mediaSourceId = &mediaSourceId
	return r
}

func (r ApiPostItemsByIdSubtitlesByIndexDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.PostItemsByIdSubtitlesByIndexDeleteExecute(r)
}

/*
PostItemsByIdSubtitlesByIndexDelete Deletes an external subtitle file

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param index The subtitle stream index
 @return ApiPostItemsByIdSubtitlesByIndexDeleteRequest
*/
func (a *SubtitleServiceAPIService) PostItemsByIdSubtitlesByIndexDelete(ctx context.Context, id string, index int32) ApiPostItemsByIdSubtitlesByIndexDeleteRequest {
	return ApiPostItemsByIdSubtitlesByIndexDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		index: index,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) PostItemsByIdSubtitlesByIndexDeleteExecute(r ApiPostItemsByIdSubtitlesByIndexDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.PostItemsByIdSubtitlesByIndexDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Items/{Id}/Subtitles/{Index}/Delete"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mediaSourceId == nil {
		return nil, reportError("mediaSourceId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "MediaSourceId", r.mediaSourceId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiPostVideosByIdSubtitlesByIndexDeleteRequest struct {
	ctx context.Context
	ApiService SubtitleServiceAPI
	id string
	mediaSourceId *string
	index int32
}

// MediaSourceId
func (r ApiPostVideosByIdSubtitlesByIndexDeleteRequest) MediaSourceId(mediaSourceId string) ApiPostVideosByIdSubtitlesByIndexDeleteRequest {
	r.mediaSourceId = &mediaSourceId
	return r
}

func (r ApiPostVideosByIdSubtitlesByIndexDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.PostVideosByIdSubtitlesByIndexDeleteExecute(r)
}

/*
PostVideosByIdSubtitlesByIndexDelete Deletes an external subtitle file

Requires authentication as user

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Item Id
 @param index The subtitle stream index
 @return ApiPostVideosByIdSubtitlesByIndexDeleteRequest
*/
func (a *SubtitleServiceAPIService) PostVideosByIdSubtitlesByIndexDelete(ctx context.Context, id string, index int32) ApiPostVideosByIdSubtitlesByIndexDeleteRequest {
	return ApiPostVideosByIdSubtitlesByIndexDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		index: index,
	}
}

// Execute executes the request
func (a *SubtitleServiceAPIService) PostVideosByIdSubtitlesByIndexDeleteExecute(r ApiPostVideosByIdSubtitlesByIndexDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SubtitleServiceAPIService.PostVideosByIdSubtitlesByIndexDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/Subtitles/{Index}/Delete"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Index"+"}", url.PathEscape(parameterValueToString(r.index, "index")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.mediaSourceId == nil {
		return nil, reportError("mediaSourceId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "MediaSourceId", r.mediaSourceId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
