/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type VideoServiceAPI interface {

	/*
		GetVideosByIdByStreamfilename Gets a video stream

		Requires authentication as user

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param streamFileName
		@param id Item Id
		@return ApiGetVideosByIdByStreamfilenameRequest
	*/
	GetVideosByIdByStreamfilename(ctx context.Context, streamFileName string, id string) ApiGetVideosByIdByStreamfilenameRequest

	// GetVideosByIdByStreamfilenameExecute executes the request
	GetVideosByIdByStreamfilenameExecute(r ApiGetVideosByIdByStreamfilenameRequest) (*http.Response, error)

	/*
		GetVideosByIdStream Gets a video stream

		Requires authentication as user

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Item Id
		@return ApiGetVideosByIdStreamRequest
	*/
	GetVideosByIdStream(ctx context.Context, id string) ApiGetVideosByIdStreamRequest

	// GetVideosByIdStreamExecute executes the request
	GetVideosByIdStreamExecute(r ApiGetVideosByIdStreamRequest) (*http.Response, error)

	/*
		GetVideosByIdStreamByContainer Gets a video stream

		Requires authentication as user

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Item Id
		@param container Container
		@return ApiGetVideosByIdStreamByContainerRequest
	*/
	GetVideosByIdStreamByContainer(ctx context.Context, id string, container string) ApiGetVideosByIdStreamByContainerRequest

	// GetVideosByIdStreamByContainerExecute executes the request
	GetVideosByIdStreamByContainerExecute(r ApiGetVideosByIdStreamByContainerRequest) (*http.Response, error)

	/*
		HeadVideosByIdByStreamfilename Gets a video stream

		Requires authentication as user

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param streamFileName
		@param id Item Id
		@return ApiHeadVideosByIdByStreamfilenameRequest
	*/
	HeadVideosByIdByStreamfilename(ctx context.Context, streamFileName string, id string) ApiHeadVideosByIdByStreamfilenameRequest

	// HeadVideosByIdByStreamfilenameExecute executes the request
	HeadVideosByIdByStreamfilenameExecute(r ApiHeadVideosByIdByStreamfilenameRequest) (*http.Response, error)

	/*
		HeadVideosByIdStream Gets a video stream

		Requires authentication as user

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Item Id
		@return ApiHeadVideosByIdStreamRequest
	*/
	HeadVideosByIdStream(ctx context.Context, id string) ApiHeadVideosByIdStreamRequest

	// HeadVideosByIdStreamExecute executes the request
	HeadVideosByIdStreamExecute(r ApiHeadVideosByIdStreamRequest) (*http.Response, error)

	/*
		HeadVideosByIdStreamByContainer Gets a video stream

		Requires authentication as user

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Item Id
		@param container Container
		@return ApiHeadVideosByIdStreamByContainerRequest
	*/
	HeadVideosByIdStreamByContainer(ctx context.Context, id string, container string) ApiHeadVideosByIdStreamByContainerRequest

	// HeadVideosByIdStreamByContainerExecute executes the request
	HeadVideosByIdStreamByContainerExecute(r ApiHeadVideosByIdStreamByContainerRequest) (*http.Response, error)
}

// VideoServiceAPIService VideoServiceAPI service
type VideoServiceAPIService service

type ApiGetVideosByIdByStreamfilenameRequest struct {
	ctx                  context.Context
	ApiService           VideoServiceAPI
	streamFileName       string
	id                   string
	container            *string
	deviceProfileId      *string
	deviceId             *string
	audioCodec           *string
	enableAutoStreamCopy *bool
	audioSampleRate      *int32
	audioBitRate         *int32
	audioChannels        *int32
	maxAudioChannels     *int32
	static               *bool
	copyTimestamps       *bool
	startTimeTicks       *int64
	width                *int32
	height               *int32
	maxWidth             *int32
	maxHeight            *int32
	videoBitRate         *int32
	subtitleStreamIndex  *int32
	subtitleMethod       *SubtitleDeliveryMethod
	maxVideoBitDepth     *int32
	videoCodec           *string
	audioStreamIndex     *int32
	videoStreamIndex     *int32
}

// Container
func (r ApiGetVideosByIdByStreamfilenameRequest) Container(container string) ApiGetVideosByIdByStreamfilenameRequest {
	r.container = &container
	return r
}

// Optional. The dlna device profile id to utilize.
func (r ApiGetVideosByIdByStreamfilenameRequest) DeviceProfileId(deviceProfileId string) ApiGetVideosByIdByStreamfilenameRequest {
	r.deviceProfileId = &deviceProfileId
	return r
}

// The device id of the client requesting. Used to stop encoding processes when needed.
func (r ApiGetVideosByIdByStreamfilenameRequest) DeviceId(deviceId string) ApiGetVideosByIdByStreamfilenameRequest {
	r.deviceId = &deviceId
	return r
}

// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#39;s extension. Options: aac, mp3, vorbis, wma.
func (r ApiGetVideosByIdByStreamfilenameRequest) AudioCodec(audioCodec string) ApiGetVideosByIdByStreamfilenameRequest {
	r.audioCodec = &audioCodec
	return r
}

// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
func (r ApiGetVideosByIdByStreamfilenameRequest) EnableAutoStreamCopy(enableAutoStreamCopy bool) ApiGetVideosByIdByStreamfilenameRequest {
	r.enableAutoStreamCopy = &enableAutoStreamCopy
	return r
}

// Optional. Specify a specific audio sample rate, e.g. 44100
func (r ApiGetVideosByIdByStreamfilenameRequest) AudioSampleRate(audioSampleRate int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.audioSampleRate = &audioSampleRate
	return r
}

// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
func (r ApiGetVideosByIdByStreamfilenameRequest) AudioBitRate(audioBitRate int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.audioBitRate = &audioBitRate
	return r
}

// Optional. Specify a specific number of audio channels to encode to, e.g. 2
func (r ApiGetVideosByIdByStreamfilenameRequest) AudioChannels(audioChannels int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.audioChannels = &audioChannels
	return r
}

// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
func (r ApiGetVideosByIdByStreamfilenameRequest) MaxAudioChannels(maxAudioChannels int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.maxAudioChannels = &maxAudioChannels
	return r
}

// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
func (r ApiGetVideosByIdByStreamfilenameRequest) Static(static bool) ApiGetVideosByIdByStreamfilenameRequest {
	r.static = &static
	return r
}

// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
func (r ApiGetVideosByIdByStreamfilenameRequest) CopyTimestamps(copyTimestamps bool) ApiGetVideosByIdByStreamfilenameRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

// Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks.
func (r ApiGetVideosByIdByStreamfilenameRequest) StartTimeTicks(startTimeTicks int64) ApiGetVideosByIdByStreamfilenameRequest {
	r.startTimeTicks = &startTimeTicks
	return r
}

// Optional. The fixed horizontal resolution of the encoded video.
func (r ApiGetVideosByIdByStreamfilenameRequest) Width(width int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.width = &width
	return r
}

// Optional. The fixed vertical resolution of the encoded video.
func (r ApiGetVideosByIdByStreamfilenameRequest) Height(height int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.height = &height
	return r
}

// Optional. The maximum horizontal resolution of the encoded video.
func (r ApiGetVideosByIdByStreamfilenameRequest) MaxWidth(maxWidth int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.maxWidth = &maxWidth
	return r
}

// Optional. The maximum vertical resolution of the encoded video.
func (r ApiGetVideosByIdByStreamfilenameRequest) MaxHeight(maxHeight int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.maxHeight = &maxHeight
	return r
}

// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
func (r ApiGetVideosByIdByStreamfilenameRequest) VideoBitRate(videoBitRate int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.videoBitRate = &videoBitRate
	return r
}

// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
func (r ApiGetVideosByIdByStreamfilenameRequest) SubtitleStreamIndex(subtitleStreamIndex int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.subtitleStreamIndex = &subtitleStreamIndex
	return r
}

// Optional. Specify the subtitle delivery method.
func (r ApiGetVideosByIdByStreamfilenameRequest) SubtitleMethod(subtitleMethod SubtitleDeliveryMethod) ApiGetVideosByIdByStreamfilenameRequest {
	r.subtitleMethod = &subtitleMethod
	return r
}

// Optional.
func (r ApiGetVideosByIdByStreamfilenameRequest) MaxVideoBitDepth(maxVideoBitDepth int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.maxVideoBitDepth = &maxVideoBitDepth
	return r
}

// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#39;s extension. Options: h264, mpeg4, theora, vpx, wmv.
func (r ApiGetVideosByIdByStreamfilenameRequest) VideoCodec(videoCodec string) ApiGetVideosByIdByStreamfilenameRequest {
	r.videoCodec = &videoCodec
	return r
}

// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
func (r ApiGetVideosByIdByStreamfilenameRequest) AudioStreamIndex(audioStreamIndex int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.audioStreamIndex = &audioStreamIndex
	return r
}

// Optional. The index of the video stream to use. If omitted the first video stream will be used.
func (r ApiGetVideosByIdByStreamfilenameRequest) VideoStreamIndex(videoStreamIndex int32) ApiGetVideosByIdByStreamfilenameRequest {
	r.videoStreamIndex = &videoStreamIndex
	return r
}

func (r ApiGetVideosByIdByStreamfilenameRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetVideosByIdByStreamfilenameExecute(r)
}

/*
GetVideosByIdByStreamfilename Gets a video stream

Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param streamFileName
	@param id Item Id
	@return ApiGetVideosByIdByStreamfilenameRequest
*/
func (a *VideoServiceAPIService) GetVideosByIdByStreamfilename(ctx context.Context, streamFileName string, id string) ApiGetVideosByIdByStreamfilenameRequest {
	return ApiGetVideosByIdByStreamfilenameRequest{
		ApiService:     a,
		ctx:            ctx,
		streamFileName: streamFileName,
		id:             id,
	}
}

// Execute executes the request
func (a *VideoServiceAPIService) GetVideosByIdByStreamfilenameExecute(r ApiGetVideosByIdByStreamfilenameRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoServiceAPIService.GetVideosByIdByStreamfilename")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{StreamFileName}"
	localVarPath = strings.Replace(localVarPath, "{"+"StreamFileName"+"}", url.PathEscape(parameterValueToString(r.streamFileName, "streamFileName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.container == nil {
		return nil, reportError("container is required and must be specified")
	}

	if r.deviceProfileId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceProfileId", r.deviceProfileId, "form", "")
	}
	if r.deviceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceId", r.deviceId, "form", "")
	}
	parameterAddToHeaderOrQuery(localVarQueryParams, "Container", r.container, "form", "")
	if r.audioCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioCodec", r.audioCodec, "form", "")
	}
	if r.enableAutoStreamCopy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EnableAutoStreamCopy", r.enableAutoStreamCopy, "form", "")
	}
	if r.audioSampleRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioSampleRate", r.audioSampleRate, "form", "")
	}
	if r.audioBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioBitRate", r.audioBitRate, "form", "")
	}
	if r.audioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioChannels", r.audioChannels, "form", "")
	}
	if r.maxAudioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxAudioChannels", r.maxAudioChannels, "form", "")
	}
	if r.static != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Static", r.static, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	if r.startTimeTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartTimeTicks", r.startTimeTicks, "form", "")
	}
	if r.width != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Width", r.width, "form", "")
	}
	if r.height != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Height", r.height, "form", "")
	}
	if r.maxWidth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxWidth", r.maxWidth, "form", "")
	}
	if r.maxHeight != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxHeight", r.maxHeight, "form", "")
	}
	if r.videoBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoBitRate", r.videoBitRate, "form", "")
	}
	if r.subtitleStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleStreamIndex", r.subtitleStreamIndex, "form", "")
	}
	if r.subtitleMethod != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleMethod", r.subtitleMethod, "form", "")
	}
	if r.maxVideoBitDepth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxVideoBitDepth", r.maxVideoBitDepth, "form", "")
	}
	if r.videoCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoCodec", r.videoCodec, "form", "")
	}
	if r.audioStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioStreamIndex", r.audioStreamIndex, "form", "")
	}
	if r.videoStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoStreamIndex", r.videoStreamIndex, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetVideosByIdStreamRequest struct {
	ctx                  context.Context
	ApiService           VideoServiceAPI
	id                   string
	container            *string
	deviceProfileId      *string
	deviceId             *string
	audioCodec           *string
	enableAutoStreamCopy *bool
	audioSampleRate      *int32
	audioBitRate         *int32
	audioChannels        *int32
	maxAudioChannels     *int32
	static               *bool
	copyTimestamps       *bool
	startTimeTicks       *int64
	width                *int32
	height               *int32
	maxWidth             *int32
	maxHeight            *int32
	videoBitRate         *int32
	subtitleStreamIndex  *int32
	subtitleMethod       *SubtitleDeliveryMethod
	maxVideoBitDepth     *int32
	videoCodec           *string
	audioStreamIndex     *int32
	videoStreamIndex     *int32
}

// Container
func (r ApiGetVideosByIdStreamRequest) Container(container string) ApiGetVideosByIdStreamRequest {
	r.container = &container
	return r
}

// Optional. The dlna device profile id to utilize.
func (r ApiGetVideosByIdStreamRequest) DeviceProfileId(deviceProfileId string) ApiGetVideosByIdStreamRequest {
	r.deviceProfileId = &deviceProfileId
	return r
}

// The device id of the client requesting. Used to stop encoding processes when needed.
func (r ApiGetVideosByIdStreamRequest) DeviceId(deviceId string) ApiGetVideosByIdStreamRequest {
	r.deviceId = &deviceId
	return r
}

// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#39;s extension. Options: aac, mp3, vorbis, wma.
func (r ApiGetVideosByIdStreamRequest) AudioCodec(audioCodec string) ApiGetVideosByIdStreamRequest {
	r.audioCodec = &audioCodec
	return r
}

// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
func (r ApiGetVideosByIdStreamRequest) EnableAutoStreamCopy(enableAutoStreamCopy bool) ApiGetVideosByIdStreamRequest {
	r.enableAutoStreamCopy = &enableAutoStreamCopy
	return r
}

// Optional. Specify a specific audio sample rate, e.g. 44100
func (r ApiGetVideosByIdStreamRequest) AudioSampleRate(audioSampleRate int32) ApiGetVideosByIdStreamRequest {
	r.audioSampleRate = &audioSampleRate
	return r
}

// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
func (r ApiGetVideosByIdStreamRequest) AudioBitRate(audioBitRate int32) ApiGetVideosByIdStreamRequest {
	r.audioBitRate = &audioBitRate
	return r
}

// Optional. Specify a specific number of audio channels to encode to, e.g. 2
func (r ApiGetVideosByIdStreamRequest) AudioChannels(audioChannels int32) ApiGetVideosByIdStreamRequest {
	r.audioChannels = &audioChannels
	return r
}

// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
func (r ApiGetVideosByIdStreamRequest) MaxAudioChannels(maxAudioChannels int32) ApiGetVideosByIdStreamRequest {
	r.maxAudioChannels = &maxAudioChannels
	return r
}

// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
func (r ApiGetVideosByIdStreamRequest) Static(static bool) ApiGetVideosByIdStreamRequest {
	r.static = &static
	return r
}

// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
func (r ApiGetVideosByIdStreamRequest) CopyTimestamps(copyTimestamps bool) ApiGetVideosByIdStreamRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

// Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks.
func (r ApiGetVideosByIdStreamRequest) StartTimeTicks(startTimeTicks int64) ApiGetVideosByIdStreamRequest {
	r.startTimeTicks = &startTimeTicks
	return r
}

// Optional. The fixed horizontal resolution of the encoded video.
func (r ApiGetVideosByIdStreamRequest) Width(width int32) ApiGetVideosByIdStreamRequest {
	r.width = &width
	return r
}

// Optional. The fixed vertical resolution of the encoded video.
func (r ApiGetVideosByIdStreamRequest) Height(height int32) ApiGetVideosByIdStreamRequest {
	r.height = &height
	return r
}

// Optional. The maximum horizontal resolution of the encoded video.
func (r ApiGetVideosByIdStreamRequest) MaxWidth(maxWidth int32) ApiGetVideosByIdStreamRequest {
	r.maxWidth = &maxWidth
	return r
}

// Optional. The maximum vertical resolution of the encoded video.
func (r ApiGetVideosByIdStreamRequest) MaxHeight(maxHeight int32) ApiGetVideosByIdStreamRequest {
	r.maxHeight = &maxHeight
	return r
}

// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
func (r ApiGetVideosByIdStreamRequest) VideoBitRate(videoBitRate int32) ApiGetVideosByIdStreamRequest {
	r.videoBitRate = &videoBitRate
	return r
}

// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
func (r ApiGetVideosByIdStreamRequest) SubtitleStreamIndex(subtitleStreamIndex int32) ApiGetVideosByIdStreamRequest {
	r.subtitleStreamIndex = &subtitleStreamIndex
	return r
}

// Optional. Specify the subtitle delivery method.
func (r ApiGetVideosByIdStreamRequest) SubtitleMethod(subtitleMethod SubtitleDeliveryMethod) ApiGetVideosByIdStreamRequest {
	r.subtitleMethod = &subtitleMethod
	return r
}

// Optional.
func (r ApiGetVideosByIdStreamRequest) MaxVideoBitDepth(maxVideoBitDepth int32) ApiGetVideosByIdStreamRequest {
	r.maxVideoBitDepth = &maxVideoBitDepth
	return r
}

// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#39;s extension. Options: h264, mpeg4, theora, vpx, wmv.
func (r ApiGetVideosByIdStreamRequest) VideoCodec(videoCodec string) ApiGetVideosByIdStreamRequest {
	r.videoCodec = &videoCodec
	return r
}

// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
func (r ApiGetVideosByIdStreamRequest) AudioStreamIndex(audioStreamIndex int32) ApiGetVideosByIdStreamRequest {
	r.audioStreamIndex = &audioStreamIndex
	return r
}

// Optional. The index of the video stream to use. If omitted the first video stream will be used.
func (r ApiGetVideosByIdStreamRequest) VideoStreamIndex(videoStreamIndex int32) ApiGetVideosByIdStreamRequest {
	r.videoStreamIndex = &videoStreamIndex
	return r
}

func (r ApiGetVideosByIdStreamRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetVideosByIdStreamExecute(r)
}

/*
GetVideosByIdStream Gets a video stream

Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@return ApiGetVideosByIdStreamRequest
*/
func (a *VideoServiceAPIService) GetVideosByIdStream(ctx context.Context, id string) ApiGetVideosByIdStreamRequest {
	return ApiGetVideosByIdStreamRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
func (a *VideoServiceAPIService) GetVideosByIdStreamExecute(r ApiGetVideosByIdStreamRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoServiceAPIService.GetVideosByIdStream")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/stream"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.container == nil {
		return nil, reportError("container is required and must be specified")
	}

	if r.deviceProfileId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceProfileId", r.deviceProfileId, "form", "")
	}
	if r.deviceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceId", r.deviceId, "form", "")
	}
	parameterAddToHeaderOrQuery(localVarQueryParams, "Container", r.container, "form", "")
	if r.audioCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioCodec", r.audioCodec, "form", "")
	}
	if r.enableAutoStreamCopy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EnableAutoStreamCopy", r.enableAutoStreamCopy, "form", "")
	}
	if r.audioSampleRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioSampleRate", r.audioSampleRate, "form", "")
	}
	if r.audioBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioBitRate", r.audioBitRate, "form", "")
	}
	if r.audioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioChannels", r.audioChannels, "form", "")
	}
	if r.maxAudioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxAudioChannels", r.maxAudioChannels, "form", "")
	}
	if r.static != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Static", r.static, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	if r.startTimeTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartTimeTicks", r.startTimeTicks, "form", "")
	}
	if r.width != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Width", r.width, "form", "")
	}
	if r.height != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Height", r.height, "form", "")
	}
	if r.maxWidth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxWidth", r.maxWidth, "form", "")
	}
	if r.maxHeight != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxHeight", r.maxHeight, "form", "")
	}
	if r.videoBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoBitRate", r.videoBitRate, "form", "")
	}
	if r.subtitleStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleStreamIndex", r.subtitleStreamIndex, "form", "")
	}
	if r.subtitleMethod != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleMethod", r.subtitleMethod, "form", "")
	}
	if r.maxVideoBitDepth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxVideoBitDepth", r.maxVideoBitDepth, "form", "")
	}
	if r.videoCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoCodec", r.videoCodec, "form", "")
	}
	if r.audioStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioStreamIndex", r.audioStreamIndex, "form", "")
	}
	if r.videoStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoStreamIndex", r.videoStreamIndex, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetVideosByIdStreamByContainerRequest struct {
	ctx                  context.Context
	ApiService           VideoServiceAPI
	id                   string
	container            string
	deviceProfileId      *string
	deviceId             *string
	audioCodec           *string
	enableAutoStreamCopy *bool
	audioSampleRate      *int32
	audioBitRate         *int32
	audioChannels        *int32
	maxAudioChannels     *int32
	static               *bool
	copyTimestamps       *bool
	startTimeTicks       *int64
	width                *int32
	height               *int32
	maxWidth             *int32
	maxHeight            *int32
	videoBitRate         *int32
	subtitleStreamIndex  *int32
	subtitleMethod       *SubtitleDeliveryMethod
	maxVideoBitDepth     *int32
	videoCodec           *string
	audioStreamIndex     *int32
	videoStreamIndex     *int32
}

// Optional. The dlna device profile id to utilize.
func (r ApiGetVideosByIdStreamByContainerRequest) DeviceProfileId(deviceProfileId string) ApiGetVideosByIdStreamByContainerRequest {
	r.deviceProfileId = &deviceProfileId
	return r
}

// The device id of the client requesting. Used to stop encoding processes when needed.
func (r ApiGetVideosByIdStreamByContainerRequest) DeviceId(deviceId string) ApiGetVideosByIdStreamByContainerRequest {
	r.deviceId = &deviceId
	return r
}

// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#39;s extension. Options: aac, mp3, vorbis, wma.
func (r ApiGetVideosByIdStreamByContainerRequest) AudioCodec(audioCodec string) ApiGetVideosByIdStreamByContainerRequest {
	r.audioCodec = &audioCodec
	return r
}

// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
func (r ApiGetVideosByIdStreamByContainerRequest) EnableAutoStreamCopy(enableAutoStreamCopy bool) ApiGetVideosByIdStreamByContainerRequest {
	r.enableAutoStreamCopy = &enableAutoStreamCopy
	return r
}

// Optional. Specify a specific audio sample rate, e.g. 44100
func (r ApiGetVideosByIdStreamByContainerRequest) AudioSampleRate(audioSampleRate int32) ApiGetVideosByIdStreamByContainerRequest {
	r.audioSampleRate = &audioSampleRate
	return r
}

// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
func (r ApiGetVideosByIdStreamByContainerRequest) AudioBitRate(audioBitRate int32) ApiGetVideosByIdStreamByContainerRequest {
	r.audioBitRate = &audioBitRate
	return r
}

// Optional. Specify a specific number of audio channels to encode to, e.g. 2
func (r ApiGetVideosByIdStreamByContainerRequest) AudioChannels(audioChannels int32) ApiGetVideosByIdStreamByContainerRequest {
	r.audioChannels = &audioChannels
	return r
}

// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
func (r ApiGetVideosByIdStreamByContainerRequest) MaxAudioChannels(maxAudioChannels int32) ApiGetVideosByIdStreamByContainerRequest {
	r.maxAudioChannels = &maxAudioChannels
	return r
}

// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
func (r ApiGetVideosByIdStreamByContainerRequest) Static(static bool) ApiGetVideosByIdStreamByContainerRequest {
	r.static = &static
	return r
}

// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
func (r ApiGetVideosByIdStreamByContainerRequest) CopyTimestamps(copyTimestamps bool) ApiGetVideosByIdStreamByContainerRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

// Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks.
func (r ApiGetVideosByIdStreamByContainerRequest) StartTimeTicks(startTimeTicks int64) ApiGetVideosByIdStreamByContainerRequest {
	r.startTimeTicks = &startTimeTicks
	return r
}

// Optional. The fixed horizontal resolution of the encoded video.
func (r ApiGetVideosByIdStreamByContainerRequest) Width(width int32) ApiGetVideosByIdStreamByContainerRequest {
	r.width = &width
	return r
}

// Optional. The fixed vertical resolution of the encoded video.
func (r ApiGetVideosByIdStreamByContainerRequest) Height(height int32) ApiGetVideosByIdStreamByContainerRequest {
	r.height = &height
	return r
}

// Optional. The maximum horizontal resolution of the encoded video.
func (r ApiGetVideosByIdStreamByContainerRequest) MaxWidth(maxWidth int32) ApiGetVideosByIdStreamByContainerRequest {
	r.maxWidth = &maxWidth
	return r
}

// Optional. The maximum vertical resolution of the encoded video.
func (r ApiGetVideosByIdStreamByContainerRequest) MaxHeight(maxHeight int32) ApiGetVideosByIdStreamByContainerRequest {
	r.maxHeight = &maxHeight
	return r
}

// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
func (r ApiGetVideosByIdStreamByContainerRequest) VideoBitRate(videoBitRate int32) ApiGetVideosByIdStreamByContainerRequest {
	r.videoBitRate = &videoBitRate
	return r
}

// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
func (r ApiGetVideosByIdStreamByContainerRequest) SubtitleStreamIndex(subtitleStreamIndex int32) ApiGetVideosByIdStreamByContainerRequest {
	r.subtitleStreamIndex = &subtitleStreamIndex
	return r
}

// Optional. Specify the subtitle delivery method.
func (r ApiGetVideosByIdStreamByContainerRequest) SubtitleMethod(subtitleMethod SubtitleDeliveryMethod) ApiGetVideosByIdStreamByContainerRequest {
	r.subtitleMethod = &subtitleMethod
	return r
}

// Optional.
func (r ApiGetVideosByIdStreamByContainerRequest) MaxVideoBitDepth(maxVideoBitDepth int32) ApiGetVideosByIdStreamByContainerRequest {
	r.maxVideoBitDepth = &maxVideoBitDepth
	return r
}

// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#39;s extension. Options: h264, mpeg4, theora, vpx, wmv.
func (r ApiGetVideosByIdStreamByContainerRequest) VideoCodec(videoCodec string) ApiGetVideosByIdStreamByContainerRequest {
	r.videoCodec = &videoCodec
	return r
}

// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
func (r ApiGetVideosByIdStreamByContainerRequest) AudioStreamIndex(audioStreamIndex int32) ApiGetVideosByIdStreamByContainerRequest {
	r.audioStreamIndex = &audioStreamIndex
	return r
}

// Optional. The index of the video stream to use. If omitted the first video stream will be used.
func (r ApiGetVideosByIdStreamByContainerRequest) VideoStreamIndex(videoStreamIndex int32) ApiGetVideosByIdStreamByContainerRequest {
	r.videoStreamIndex = &videoStreamIndex
	return r
}

func (r ApiGetVideosByIdStreamByContainerRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetVideosByIdStreamByContainerExecute(r)
}

/*
GetVideosByIdStreamByContainer Gets a video stream

Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param container Container
	@return ApiGetVideosByIdStreamByContainerRequest
*/
func (a *VideoServiceAPIService) GetVideosByIdStreamByContainer(ctx context.Context, id string, container string) ApiGetVideosByIdStreamByContainerRequest {
	return ApiGetVideosByIdStreamByContainerRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
		container:  container,
	}
}

// Execute executes the request
func (a *VideoServiceAPIService) GetVideosByIdStreamByContainerExecute(r ApiGetVideosByIdStreamByContainerRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoServiceAPIService.GetVideosByIdStreamByContainer")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/stream.{Container}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Container"+"}", url.PathEscape(parameterValueToString(r.container, "container")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.deviceProfileId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceProfileId", r.deviceProfileId, "form", "")
	}
	if r.deviceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceId", r.deviceId, "form", "")
	}
	if r.audioCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioCodec", r.audioCodec, "form", "")
	}
	if r.enableAutoStreamCopy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EnableAutoStreamCopy", r.enableAutoStreamCopy, "form", "")
	}
	if r.audioSampleRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioSampleRate", r.audioSampleRate, "form", "")
	}
	if r.audioBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioBitRate", r.audioBitRate, "form", "")
	}
	if r.audioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioChannels", r.audioChannels, "form", "")
	}
	if r.maxAudioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxAudioChannels", r.maxAudioChannels, "form", "")
	}
	if r.static != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Static", r.static, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	if r.startTimeTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartTimeTicks", r.startTimeTicks, "form", "")
	}
	if r.width != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Width", r.width, "form", "")
	}
	if r.height != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Height", r.height, "form", "")
	}
	if r.maxWidth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxWidth", r.maxWidth, "form", "")
	}
	if r.maxHeight != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxHeight", r.maxHeight, "form", "")
	}
	if r.videoBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoBitRate", r.videoBitRate, "form", "")
	}
	if r.subtitleStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleStreamIndex", r.subtitleStreamIndex, "form", "")
	}
	if r.subtitleMethod != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleMethod", r.subtitleMethod, "form", "")
	}
	if r.maxVideoBitDepth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxVideoBitDepth", r.maxVideoBitDepth, "form", "")
	}
	if r.videoCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoCodec", r.videoCodec, "form", "")
	}
	if r.audioStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioStreamIndex", r.audioStreamIndex, "form", "")
	}
	if r.videoStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoStreamIndex", r.videoStreamIndex, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadVideosByIdByStreamfilenameRequest struct {
	ctx                  context.Context
	ApiService           VideoServiceAPI
	streamFileName       string
	id                   string
	container            *string
	deviceProfileId      *string
	deviceId             *string
	audioCodec           *string
	enableAutoStreamCopy *bool
	audioSampleRate      *int32
	audioBitRate         *int32
	audioChannels        *int32
	maxAudioChannels     *int32
	static               *bool
	copyTimestamps       *bool
	startTimeTicks       *int64
	width                *int32
	height               *int32
	maxWidth             *int32
	maxHeight            *int32
	videoBitRate         *int32
	subtitleStreamIndex  *int32
	subtitleMethod       *SubtitleDeliveryMethod
	maxVideoBitDepth     *int32
	videoCodec           *string
	audioStreamIndex     *int32
	videoStreamIndex     *int32
}

// Container
func (r ApiHeadVideosByIdByStreamfilenameRequest) Container(container string) ApiHeadVideosByIdByStreamfilenameRequest {
	r.container = &container
	return r
}

// Optional. The dlna device profile id to utilize.
func (r ApiHeadVideosByIdByStreamfilenameRequest) DeviceProfileId(deviceProfileId string) ApiHeadVideosByIdByStreamfilenameRequest {
	r.deviceProfileId = &deviceProfileId
	return r
}

// The device id of the client requesting. Used to stop encoding processes when needed.
func (r ApiHeadVideosByIdByStreamfilenameRequest) DeviceId(deviceId string) ApiHeadVideosByIdByStreamfilenameRequest {
	r.deviceId = &deviceId
	return r
}

// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#39;s extension. Options: aac, mp3, vorbis, wma.
func (r ApiHeadVideosByIdByStreamfilenameRequest) AudioCodec(audioCodec string) ApiHeadVideosByIdByStreamfilenameRequest {
	r.audioCodec = &audioCodec
	return r
}

// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
func (r ApiHeadVideosByIdByStreamfilenameRequest) EnableAutoStreamCopy(enableAutoStreamCopy bool) ApiHeadVideosByIdByStreamfilenameRequest {
	r.enableAutoStreamCopy = &enableAutoStreamCopy
	return r
}

// Optional. Specify a specific audio sample rate, e.g. 44100
func (r ApiHeadVideosByIdByStreamfilenameRequest) AudioSampleRate(audioSampleRate int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.audioSampleRate = &audioSampleRate
	return r
}

// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
func (r ApiHeadVideosByIdByStreamfilenameRequest) AudioBitRate(audioBitRate int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.audioBitRate = &audioBitRate
	return r
}

// Optional. Specify a specific number of audio channels to encode to, e.g. 2
func (r ApiHeadVideosByIdByStreamfilenameRequest) AudioChannels(audioChannels int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.audioChannels = &audioChannels
	return r
}

// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
func (r ApiHeadVideosByIdByStreamfilenameRequest) MaxAudioChannels(maxAudioChannels int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.maxAudioChannels = &maxAudioChannels
	return r
}

// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
func (r ApiHeadVideosByIdByStreamfilenameRequest) Static(static bool) ApiHeadVideosByIdByStreamfilenameRequest {
	r.static = &static
	return r
}

// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
func (r ApiHeadVideosByIdByStreamfilenameRequest) CopyTimestamps(copyTimestamps bool) ApiHeadVideosByIdByStreamfilenameRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

// Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks.
func (r ApiHeadVideosByIdByStreamfilenameRequest) StartTimeTicks(startTimeTicks int64) ApiHeadVideosByIdByStreamfilenameRequest {
	r.startTimeTicks = &startTimeTicks
	return r
}

// Optional. The fixed horizontal resolution of the encoded video.
func (r ApiHeadVideosByIdByStreamfilenameRequest) Width(width int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.width = &width
	return r
}

// Optional. The fixed vertical resolution of the encoded video.
func (r ApiHeadVideosByIdByStreamfilenameRequest) Height(height int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.height = &height
	return r
}

// Optional. The maximum horizontal resolution of the encoded video.
func (r ApiHeadVideosByIdByStreamfilenameRequest) MaxWidth(maxWidth int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.maxWidth = &maxWidth
	return r
}

// Optional. The maximum vertical resolution of the encoded video.
func (r ApiHeadVideosByIdByStreamfilenameRequest) MaxHeight(maxHeight int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.maxHeight = &maxHeight
	return r
}

// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
func (r ApiHeadVideosByIdByStreamfilenameRequest) VideoBitRate(videoBitRate int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.videoBitRate = &videoBitRate
	return r
}

// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
func (r ApiHeadVideosByIdByStreamfilenameRequest) SubtitleStreamIndex(subtitleStreamIndex int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.subtitleStreamIndex = &subtitleStreamIndex
	return r
}

// Optional. Specify the subtitle delivery method.
func (r ApiHeadVideosByIdByStreamfilenameRequest) SubtitleMethod(subtitleMethod SubtitleDeliveryMethod) ApiHeadVideosByIdByStreamfilenameRequest {
	r.subtitleMethod = &subtitleMethod
	return r
}

// Optional.
func (r ApiHeadVideosByIdByStreamfilenameRequest) MaxVideoBitDepth(maxVideoBitDepth int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.maxVideoBitDepth = &maxVideoBitDepth
	return r
}

// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#39;s extension. Options: h264, mpeg4, theora, vpx, wmv.
func (r ApiHeadVideosByIdByStreamfilenameRequest) VideoCodec(videoCodec string) ApiHeadVideosByIdByStreamfilenameRequest {
	r.videoCodec = &videoCodec
	return r
}

// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
func (r ApiHeadVideosByIdByStreamfilenameRequest) AudioStreamIndex(audioStreamIndex int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.audioStreamIndex = &audioStreamIndex
	return r
}

// Optional. The index of the video stream to use. If omitted the first video stream will be used.
func (r ApiHeadVideosByIdByStreamfilenameRequest) VideoStreamIndex(videoStreamIndex int32) ApiHeadVideosByIdByStreamfilenameRequest {
	r.videoStreamIndex = &videoStreamIndex
	return r
}

func (r ApiHeadVideosByIdByStreamfilenameRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadVideosByIdByStreamfilenameExecute(r)
}

/*
HeadVideosByIdByStreamfilename Gets a video stream

Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param streamFileName
	@param id Item Id
	@return ApiHeadVideosByIdByStreamfilenameRequest
*/
func (a *VideoServiceAPIService) HeadVideosByIdByStreamfilename(ctx context.Context, streamFileName string, id string) ApiHeadVideosByIdByStreamfilenameRequest {
	return ApiHeadVideosByIdByStreamfilenameRequest{
		ApiService:     a,
		ctx:            ctx,
		streamFileName: streamFileName,
		id:             id,
	}
}

// Execute executes the request
func (a *VideoServiceAPIService) HeadVideosByIdByStreamfilenameExecute(r ApiHeadVideosByIdByStreamfilenameRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodHead
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoServiceAPIService.HeadVideosByIdByStreamfilename")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/{StreamFileName}"
	localVarPath = strings.Replace(localVarPath, "{"+"StreamFileName"+"}", url.PathEscape(parameterValueToString(r.streamFileName, "streamFileName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.container == nil {
		return nil, reportError("container is required and must be specified")
	}

	if r.deviceProfileId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceProfileId", r.deviceProfileId, "form", "")
	}
	if r.deviceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceId", r.deviceId, "form", "")
	}
	parameterAddToHeaderOrQuery(localVarQueryParams, "Container", r.container, "form", "")
	if r.audioCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioCodec", r.audioCodec, "form", "")
	}
	if r.enableAutoStreamCopy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EnableAutoStreamCopy", r.enableAutoStreamCopy, "form", "")
	}
	if r.audioSampleRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioSampleRate", r.audioSampleRate, "form", "")
	}
	if r.audioBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioBitRate", r.audioBitRate, "form", "")
	}
	if r.audioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioChannels", r.audioChannels, "form", "")
	}
	if r.maxAudioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxAudioChannels", r.maxAudioChannels, "form", "")
	}
	if r.static != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Static", r.static, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	if r.startTimeTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartTimeTicks", r.startTimeTicks, "form", "")
	}
	if r.width != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Width", r.width, "form", "")
	}
	if r.height != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Height", r.height, "form", "")
	}
	if r.maxWidth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxWidth", r.maxWidth, "form", "")
	}
	if r.maxHeight != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxHeight", r.maxHeight, "form", "")
	}
	if r.videoBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoBitRate", r.videoBitRate, "form", "")
	}
	if r.subtitleStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleStreamIndex", r.subtitleStreamIndex, "form", "")
	}
	if r.subtitleMethod != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleMethod", r.subtitleMethod, "form", "")
	}
	if r.maxVideoBitDepth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxVideoBitDepth", r.maxVideoBitDepth, "form", "")
	}
	if r.videoCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoCodec", r.videoCodec, "form", "")
	}
	if r.audioStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioStreamIndex", r.audioStreamIndex, "form", "")
	}
	if r.videoStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoStreamIndex", r.videoStreamIndex, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadVideosByIdStreamRequest struct {
	ctx                  context.Context
	ApiService           VideoServiceAPI
	id                   string
	container            *string
	deviceProfileId      *string
	deviceId             *string
	audioCodec           *string
	enableAutoStreamCopy *bool
	audioSampleRate      *int32
	audioBitRate         *int32
	audioChannels        *int32
	maxAudioChannels     *int32
	static               *bool
	copyTimestamps       *bool
	startTimeTicks       *int64
	width                *int32
	height               *int32
	maxWidth             *int32
	maxHeight            *int32
	videoBitRate         *int32
	subtitleStreamIndex  *int32
	subtitleMethod       *SubtitleDeliveryMethod
	maxVideoBitDepth     *int32
	videoCodec           *string
	audioStreamIndex     *int32
	videoStreamIndex     *int32
}

// Container
func (r ApiHeadVideosByIdStreamRequest) Container(container string) ApiHeadVideosByIdStreamRequest {
	r.container = &container
	return r
}

// Optional. The dlna device profile id to utilize.
func (r ApiHeadVideosByIdStreamRequest) DeviceProfileId(deviceProfileId string) ApiHeadVideosByIdStreamRequest {
	r.deviceProfileId = &deviceProfileId
	return r
}

// The device id of the client requesting. Used to stop encoding processes when needed.
func (r ApiHeadVideosByIdStreamRequest) DeviceId(deviceId string) ApiHeadVideosByIdStreamRequest {
	r.deviceId = &deviceId
	return r
}

// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#39;s extension. Options: aac, mp3, vorbis, wma.
func (r ApiHeadVideosByIdStreamRequest) AudioCodec(audioCodec string) ApiHeadVideosByIdStreamRequest {
	r.audioCodec = &audioCodec
	return r
}

// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
func (r ApiHeadVideosByIdStreamRequest) EnableAutoStreamCopy(enableAutoStreamCopy bool) ApiHeadVideosByIdStreamRequest {
	r.enableAutoStreamCopy = &enableAutoStreamCopy
	return r
}

// Optional. Specify a specific audio sample rate, e.g. 44100
func (r ApiHeadVideosByIdStreamRequest) AudioSampleRate(audioSampleRate int32) ApiHeadVideosByIdStreamRequest {
	r.audioSampleRate = &audioSampleRate
	return r
}

// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
func (r ApiHeadVideosByIdStreamRequest) AudioBitRate(audioBitRate int32) ApiHeadVideosByIdStreamRequest {
	r.audioBitRate = &audioBitRate
	return r
}

// Optional. Specify a specific number of audio channels to encode to, e.g. 2
func (r ApiHeadVideosByIdStreamRequest) AudioChannels(audioChannels int32) ApiHeadVideosByIdStreamRequest {
	r.audioChannels = &audioChannels
	return r
}

// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
func (r ApiHeadVideosByIdStreamRequest) MaxAudioChannels(maxAudioChannels int32) ApiHeadVideosByIdStreamRequest {
	r.maxAudioChannels = &maxAudioChannels
	return r
}

// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
func (r ApiHeadVideosByIdStreamRequest) Static(static bool) ApiHeadVideosByIdStreamRequest {
	r.static = &static
	return r
}

// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
func (r ApiHeadVideosByIdStreamRequest) CopyTimestamps(copyTimestamps bool) ApiHeadVideosByIdStreamRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

// Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks.
func (r ApiHeadVideosByIdStreamRequest) StartTimeTicks(startTimeTicks int64) ApiHeadVideosByIdStreamRequest {
	r.startTimeTicks = &startTimeTicks
	return r
}

// Optional. The fixed horizontal resolution of the encoded video.
func (r ApiHeadVideosByIdStreamRequest) Width(width int32) ApiHeadVideosByIdStreamRequest {
	r.width = &width
	return r
}

// Optional. The fixed vertical resolution of the encoded video.
func (r ApiHeadVideosByIdStreamRequest) Height(height int32) ApiHeadVideosByIdStreamRequest {
	r.height = &height
	return r
}

// Optional. The maximum horizontal resolution of the encoded video.
func (r ApiHeadVideosByIdStreamRequest) MaxWidth(maxWidth int32) ApiHeadVideosByIdStreamRequest {
	r.maxWidth = &maxWidth
	return r
}

// Optional. The maximum vertical resolution of the encoded video.
func (r ApiHeadVideosByIdStreamRequest) MaxHeight(maxHeight int32) ApiHeadVideosByIdStreamRequest {
	r.maxHeight = &maxHeight
	return r
}

// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
func (r ApiHeadVideosByIdStreamRequest) VideoBitRate(videoBitRate int32) ApiHeadVideosByIdStreamRequest {
	r.videoBitRate = &videoBitRate
	return r
}

// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
func (r ApiHeadVideosByIdStreamRequest) SubtitleStreamIndex(subtitleStreamIndex int32) ApiHeadVideosByIdStreamRequest {
	r.subtitleStreamIndex = &subtitleStreamIndex
	return r
}

// Optional. Specify the subtitle delivery method.
func (r ApiHeadVideosByIdStreamRequest) SubtitleMethod(subtitleMethod SubtitleDeliveryMethod) ApiHeadVideosByIdStreamRequest {
	r.subtitleMethod = &subtitleMethod
	return r
}

// Optional.
func (r ApiHeadVideosByIdStreamRequest) MaxVideoBitDepth(maxVideoBitDepth int32) ApiHeadVideosByIdStreamRequest {
	r.maxVideoBitDepth = &maxVideoBitDepth
	return r
}

// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#39;s extension. Options: h264, mpeg4, theora, vpx, wmv.
func (r ApiHeadVideosByIdStreamRequest) VideoCodec(videoCodec string) ApiHeadVideosByIdStreamRequest {
	r.videoCodec = &videoCodec
	return r
}

// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
func (r ApiHeadVideosByIdStreamRequest) AudioStreamIndex(audioStreamIndex int32) ApiHeadVideosByIdStreamRequest {
	r.audioStreamIndex = &audioStreamIndex
	return r
}

// Optional. The index of the video stream to use. If omitted the first video stream will be used.
func (r ApiHeadVideosByIdStreamRequest) VideoStreamIndex(videoStreamIndex int32) ApiHeadVideosByIdStreamRequest {
	r.videoStreamIndex = &videoStreamIndex
	return r
}

func (r ApiHeadVideosByIdStreamRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadVideosByIdStreamExecute(r)
}

/*
HeadVideosByIdStream Gets a video stream

Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@return ApiHeadVideosByIdStreamRequest
*/
func (a *VideoServiceAPIService) HeadVideosByIdStream(ctx context.Context, id string) ApiHeadVideosByIdStreamRequest {
	return ApiHeadVideosByIdStreamRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
func (a *VideoServiceAPIService) HeadVideosByIdStreamExecute(r ApiHeadVideosByIdStreamRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodHead
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoServiceAPIService.HeadVideosByIdStream")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/stream"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.container == nil {
		return nil, reportError("container is required and must be specified")
	}

	if r.deviceProfileId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceProfileId", r.deviceProfileId, "form", "")
	}
	if r.deviceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceId", r.deviceId, "form", "")
	}
	parameterAddToHeaderOrQuery(localVarQueryParams, "Container", r.container, "form", "")
	if r.audioCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioCodec", r.audioCodec, "form", "")
	}
	if r.enableAutoStreamCopy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EnableAutoStreamCopy", r.enableAutoStreamCopy, "form", "")
	}
	if r.audioSampleRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioSampleRate", r.audioSampleRate, "form", "")
	}
	if r.audioBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioBitRate", r.audioBitRate, "form", "")
	}
	if r.audioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioChannels", r.audioChannels, "form", "")
	}
	if r.maxAudioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxAudioChannels", r.maxAudioChannels, "form", "")
	}
	if r.static != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Static", r.static, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	if r.startTimeTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartTimeTicks", r.startTimeTicks, "form", "")
	}
	if r.width != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Width", r.width, "form", "")
	}
	if r.height != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Height", r.height, "form", "")
	}
	if r.maxWidth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxWidth", r.maxWidth, "form", "")
	}
	if r.maxHeight != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxHeight", r.maxHeight, "form", "")
	}
	if r.videoBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoBitRate", r.videoBitRate, "form", "")
	}
	if r.subtitleStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleStreamIndex", r.subtitleStreamIndex, "form", "")
	}
	if r.subtitleMethod != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleMethod", r.subtitleMethod, "form", "")
	}
	if r.maxVideoBitDepth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxVideoBitDepth", r.maxVideoBitDepth, "form", "")
	}
	if r.videoCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoCodec", r.videoCodec, "form", "")
	}
	if r.audioStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioStreamIndex", r.audioStreamIndex, "form", "")
	}
	if r.videoStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoStreamIndex", r.videoStreamIndex, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiHeadVideosByIdStreamByContainerRequest struct {
	ctx                  context.Context
	ApiService           VideoServiceAPI
	id                   string
	container            string
	deviceProfileId      *string
	deviceId             *string
	audioCodec           *string
	enableAutoStreamCopy *bool
	audioSampleRate      *int32
	audioBitRate         *int32
	audioChannels        *int32
	maxAudioChannels     *int32
	static               *bool
	copyTimestamps       *bool
	startTimeTicks       *int64
	width                *int32
	height               *int32
	maxWidth             *int32
	maxHeight            *int32
	videoBitRate         *int32
	subtitleStreamIndex  *int32
	subtitleMethod       *SubtitleDeliveryMethod
	maxVideoBitDepth     *int32
	videoCodec           *string
	audioStreamIndex     *int32
	videoStreamIndex     *int32
}

// Optional. The dlna device profile id to utilize.
func (r ApiHeadVideosByIdStreamByContainerRequest) DeviceProfileId(deviceProfileId string) ApiHeadVideosByIdStreamByContainerRequest {
	r.deviceProfileId = &deviceProfileId
	return r
}

// The device id of the client requesting. Used to stop encoding processes when needed.
func (r ApiHeadVideosByIdStreamByContainerRequest) DeviceId(deviceId string) ApiHeadVideosByIdStreamByContainerRequest {
	r.deviceId = &deviceId
	return r
}

// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#39;s extension. Options: aac, mp3, vorbis, wma.
func (r ApiHeadVideosByIdStreamByContainerRequest) AudioCodec(audioCodec string) ApiHeadVideosByIdStreamByContainerRequest {
	r.audioCodec = &audioCodec
	return r
}

// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
func (r ApiHeadVideosByIdStreamByContainerRequest) EnableAutoStreamCopy(enableAutoStreamCopy bool) ApiHeadVideosByIdStreamByContainerRequest {
	r.enableAutoStreamCopy = &enableAutoStreamCopy
	return r
}

// Optional. Specify a specific audio sample rate, e.g. 44100
func (r ApiHeadVideosByIdStreamByContainerRequest) AudioSampleRate(audioSampleRate int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.audioSampleRate = &audioSampleRate
	return r
}

// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
func (r ApiHeadVideosByIdStreamByContainerRequest) AudioBitRate(audioBitRate int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.audioBitRate = &audioBitRate
	return r
}

// Optional. Specify a specific number of audio channels to encode to, e.g. 2
func (r ApiHeadVideosByIdStreamByContainerRequest) AudioChannels(audioChannels int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.audioChannels = &audioChannels
	return r
}

// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
func (r ApiHeadVideosByIdStreamByContainerRequest) MaxAudioChannels(maxAudioChannels int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.maxAudioChannels = &maxAudioChannels
	return r
}

// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
func (r ApiHeadVideosByIdStreamByContainerRequest) Static(static bool) ApiHeadVideosByIdStreamByContainerRequest {
	r.static = &static
	return r
}

// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
func (r ApiHeadVideosByIdStreamByContainerRequest) CopyTimestamps(copyTimestamps bool) ApiHeadVideosByIdStreamByContainerRequest {
	r.copyTimestamps = &copyTimestamps
	return r
}

// Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks.
func (r ApiHeadVideosByIdStreamByContainerRequest) StartTimeTicks(startTimeTicks int64) ApiHeadVideosByIdStreamByContainerRequest {
	r.startTimeTicks = &startTimeTicks
	return r
}

// Optional. The fixed horizontal resolution of the encoded video.
func (r ApiHeadVideosByIdStreamByContainerRequest) Width(width int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.width = &width
	return r
}

// Optional. The fixed vertical resolution of the encoded video.
func (r ApiHeadVideosByIdStreamByContainerRequest) Height(height int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.height = &height
	return r
}

// Optional. The maximum horizontal resolution of the encoded video.
func (r ApiHeadVideosByIdStreamByContainerRequest) MaxWidth(maxWidth int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.maxWidth = &maxWidth
	return r
}

// Optional. The maximum vertical resolution of the encoded video.
func (r ApiHeadVideosByIdStreamByContainerRequest) MaxHeight(maxHeight int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.maxHeight = &maxHeight
	return r
}

// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
func (r ApiHeadVideosByIdStreamByContainerRequest) VideoBitRate(videoBitRate int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.videoBitRate = &videoBitRate
	return r
}

// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
func (r ApiHeadVideosByIdStreamByContainerRequest) SubtitleStreamIndex(subtitleStreamIndex int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.subtitleStreamIndex = &subtitleStreamIndex
	return r
}

// Optional. Specify the subtitle delivery method.
func (r ApiHeadVideosByIdStreamByContainerRequest) SubtitleMethod(subtitleMethod SubtitleDeliveryMethod) ApiHeadVideosByIdStreamByContainerRequest {
	r.subtitleMethod = &subtitleMethod
	return r
}

// Optional.
func (r ApiHeadVideosByIdStreamByContainerRequest) MaxVideoBitDepth(maxVideoBitDepth int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.maxVideoBitDepth = &maxVideoBitDepth
	return r
}

// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#39;s extension. Options: h264, mpeg4, theora, vpx, wmv.
func (r ApiHeadVideosByIdStreamByContainerRequest) VideoCodec(videoCodec string) ApiHeadVideosByIdStreamByContainerRequest {
	r.videoCodec = &videoCodec
	return r
}

// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
func (r ApiHeadVideosByIdStreamByContainerRequest) AudioStreamIndex(audioStreamIndex int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.audioStreamIndex = &audioStreamIndex
	return r
}

// Optional. The index of the video stream to use. If omitted the first video stream will be used.
func (r ApiHeadVideosByIdStreamByContainerRequest) VideoStreamIndex(videoStreamIndex int32) ApiHeadVideosByIdStreamByContainerRequest {
	r.videoStreamIndex = &videoStreamIndex
	return r
}

func (r ApiHeadVideosByIdStreamByContainerRequest) Execute() (*http.Response, error) {
	return r.ApiService.HeadVideosByIdStreamByContainerExecute(r)
}

/*
HeadVideosByIdStreamByContainer Gets a video stream

Requires authentication as user

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Item Id
	@param container Container
	@return ApiHeadVideosByIdStreamByContainerRequest
*/
func (a *VideoServiceAPIService) HeadVideosByIdStreamByContainer(ctx context.Context, id string, container string) ApiHeadVideosByIdStreamByContainerRequest {
	return ApiHeadVideosByIdStreamByContainerRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
		container:  container,
	}
}

// Execute executes the request
func (a *VideoServiceAPIService) HeadVideosByIdStreamByContainerExecute(r ApiHeadVideosByIdStreamByContainerRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodHead
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VideoServiceAPIService.HeadVideosByIdStreamByContainer")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/Videos/{Id}/stream.{Container}"
	localVarPath = strings.Replace(localVarPath, "{"+"Id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"Container"+"}", url.PathEscape(parameterValueToString(r.container, "container")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.deviceProfileId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceProfileId", r.deviceProfileId, "form", "")
	}
	if r.deviceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "DeviceId", r.deviceId, "form", "")
	}
	if r.audioCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioCodec", r.audioCodec, "form", "")
	}
	if r.enableAutoStreamCopy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "EnableAutoStreamCopy", r.enableAutoStreamCopy, "form", "")
	}
	if r.audioSampleRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioSampleRate", r.audioSampleRate, "form", "")
	}
	if r.audioBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioBitRate", r.audioBitRate, "form", "")
	}
	if r.audioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioChannels", r.audioChannels, "form", "")
	}
	if r.maxAudioChannels != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxAudioChannels", r.maxAudioChannels, "form", "")
	}
	if r.static != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Static", r.static, "form", "")
	}
	if r.copyTimestamps != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "CopyTimestamps", r.copyTimestamps, "form", "")
	}
	if r.startTimeTicks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "StartTimeTicks", r.startTimeTicks, "form", "")
	}
	if r.width != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Width", r.width, "form", "")
	}
	if r.height != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "Height", r.height, "form", "")
	}
	if r.maxWidth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxWidth", r.maxWidth, "form", "")
	}
	if r.maxHeight != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxHeight", r.maxHeight, "form", "")
	}
	if r.videoBitRate != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoBitRate", r.videoBitRate, "form", "")
	}
	if r.subtitleStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleStreamIndex", r.subtitleStreamIndex, "form", "")
	}
	if r.subtitleMethod != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "SubtitleMethod", r.subtitleMethod, "form", "")
	}
	if r.maxVideoBitDepth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "MaxVideoBitDepth", r.maxVideoBitDepth, "form", "")
	}
	if r.videoCodec != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoCodec", r.videoCodec, "form", "")
	}
	if r.audioStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "AudioStreamIndex", r.audioStreamIndex, "form", "")
	}
	if r.videoStreamIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "VideoStreamIndex", r.videoStreamIndex, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyauth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("api_key", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
