/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the Resolution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Resolution{}

// Resolution struct for Resolution
type Resolution struct {
	Width  *int32 `json:"Width,omitempty"`
	Height *int32 `json:"Height,omitempty"`
}

// NewResolution instantiates a new Resolution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolution() *Resolution {
	this := Resolution{}
	return &this
}

// NewResolutionWithDefaults instantiates a new Resolution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolutionWithDefaults() *Resolution {
	this := Resolution{}
	return &this
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Resolution) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Resolution) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *Resolution) SetWidth(v int32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Resolution) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Resolution) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *Resolution) SetHeight(v int32) {
	o.Height = &v
}

func (o Resolution) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Resolution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Width) {
		toSerialize["Width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["Height"] = o.Height
	}
	return toSerialize, nil
}

type NullableResolution struct {
	value *Resolution
	isSet bool
}

func (v NullableResolution) Get() *Resolution {
	return v.value
}

func (v *NullableResolution) Set(val *Resolution) {
	v.value = val
	v.isSet = true
}

func (v NullableResolution) IsSet() bool {
	return v.isSet
}

func (v *NullableResolution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolution(val *Resolution) *NullableResolution {
	return &NullableResolution{value: val, isSet: true}
}

func (v NullableResolution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
