/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"fmt"
)

// LiveTvTimerType the model 'LiveTvTimerType'
type LiveTvTimerType string

// List of LiveTv.TimerType
const (
	LIVETVTIMERTYPE_PROGRAM   LiveTvTimerType = "Program"
	LIVETVTIMERTYPE_DATE_TIME LiveTvTimerType = "DateTime"
	LIVETVTIMERTYPE_KEYWORD   LiveTvTimerType = "Keyword"
)

// All allowed values of LiveTvTimerType enum
var AllowedLiveTvTimerTypeEnumValues = []LiveTvTimerType{
	"Program",
	"DateTime",
	"Keyword",
}

func (v *LiveTvTimerType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LiveTvTimerType(value)
	for _, existing := range AllowedLiveTvTimerTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LiveTvTimerType", value)
}

// NewLiveTvTimerTypeFromValue returns a pointer to a valid LiveTvTimerType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLiveTvTimerTypeFromValue(v string) (*LiveTvTimerType, error) {
	ev := LiveTvTimerType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LiveTvTimerType: valid values are %v", v, AllowedLiveTvTimerTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LiveTvTimerType) IsValid() bool {
	for _, existing := range AllowedLiveTvTimerTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LiveTv.TimerType value
func (v LiveTvTimerType) Ptr() *LiveTvTimerType {
	return &v
}

type NullableLiveTvTimerType struct {
	value *LiveTvTimerType
	isSet bool
}

func (v NullableLiveTvTimerType) Get() *LiveTvTimerType {
	return v.value
}

func (v *NullableLiveTvTimerType) Set(val *LiveTvTimerType) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveTvTimerType) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveTvTimerType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveTvTimerType(val *LiveTvTimerType) *NullableLiveTvTimerType {
	return &NullableLiveTvTimerType{value: val, isSet: true}
}

func (v NullableLiveTvTimerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiveTvTimerType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
