/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the MBBackupApiRestoreOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MBBackupApiRestoreOptions{}

// MBBackupApiRestoreOptions struct for MBBackupApiRestoreOptions
type MBBackupApiRestoreOptions struct {
	RestoreServerId *bool   `json:"RestoreServerId,omitempty"`
	UseFiles        *string `json:"UseFiles,omitempty"`
}

// NewMBBackupApiRestoreOptions instantiates a new MBBackupApiRestoreOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMBBackupApiRestoreOptions() *MBBackupApiRestoreOptions {
	this := MBBackupApiRestoreOptions{}
	return &this
}

// NewMBBackupApiRestoreOptionsWithDefaults instantiates a new MBBackupApiRestoreOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMBBackupApiRestoreOptionsWithDefaults() *MBBackupApiRestoreOptions {
	this := MBBackupApiRestoreOptions{}
	return &this
}

// GetRestoreServerId returns the RestoreServerId field value if set, zero value otherwise.
func (o *MBBackupApiRestoreOptions) GetRestoreServerId() bool {
	if o == nil || IsNil(o.RestoreServerId) {
		var ret bool
		return ret
	}
	return *o.RestoreServerId
}

// GetRestoreServerIdOk returns a tuple with the RestoreServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MBBackupApiRestoreOptions) GetRestoreServerIdOk() (*bool, bool) {
	if o == nil || IsNil(o.RestoreServerId) {
		return nil, false
	}
	return o.RestoreServerId, true
}

// HasRestoreServerId returns a boolean if a field has been set.
func (o *MBBackupApiRestoreOptions) HasRestoreServerId() bool {
	if o != nil && !IsNil(o.RestoreServerId) {
		return true
	}

	return false
}

// SetRestoreServerId gets a reference to the given bool and assigns it to the RestoreServerId field.
func (o *MBBackupApiRestoreOptions) SetRestoreServerId(v bool) {
	o.RestoreServerId = &v
}

// GetUseFiles returns the UseFiles field value if set, zero value otherwise.
func (o *MBBackupApiRestoreOptions) GetUseFiles() string {
	if o == nil || IsNil(o.UseFiles) {
		var ret string
		return ret
	}
	return *o.UseFiles
}

// GetUseFilesOk returns a tuple with the UseFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MBBackupApiRestoreOptions) GetUseFilesOk() (*string, bool) {
	if o == nil || IsNil(o.UseFiles) {
		return nil, false
	}
	return o.UseFiles, true
}

// HasUseFiles returns a boolean if a field has been set.
func (o *MBBackupApiRestoreOptions) HasUseFiles() bool {
	if o != nil && !IsNil(o.UseFiles) {
		return true
	}

	return false
}

// SetUseFiles gets a reference to the given string and assigns it to the UseFiles field.
func (o *MBBackupApiRestoreOptions) SetUseFiles(v string) {
	o.UseFiles = &v
}

func (o MBBackupApiRestoreOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MBBackupApiRestoreOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RestoreServerId) {
		toSerialize["RestoreServerId"] = o.RestoreServerId
	}
	if !IsNil(o.UseFiles) {
		toSerialize["UseFiles"] = o.UseFiles
	}
	return toSerialize, nil
}

type NullableMBBackupApiRestoreOptions struct {
	value *MBBackupApiRestoreOptions
	isSet bool
}

func (v NullableMBBackupApiRestoreOptions) Get() *MBBackupApiRestoreOptions {
	return v.value
}

func (v *NullableMBBackupApiRestoreOptions) Set(val *MBBackupApiRestoreOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableMBBackupApiRestoreOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableMBBackupApiRestoreOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMBBackupApiRestoreOptions(val *MBBackupApiRestoreOptions) *NullableMBBackupApiRestoreOptions {
	return &NullableMBBackupApiRestoreOptions{value: val, isSet: true}
}

func (v NullableMBBackupApiRestoreOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMBBackupApiRestoreOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
