/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"fmt"
)

// UserActionType the model 'UserActionType'
type UserActionType string

// List of UserActionType
const (
	USERACTIONTYPE_PLAYED_ITEM   UserActionType = "PlayedItem"
	USERACTIONTYPE_MARK_PLAYED   UserActionType = "MarkPlayed"
	USERACTIONTYPE_MARK_FAVORITE UserActionType = "MarkFavorite"
)

// All allowed values of UserActionType enum
var AllowedUserActionTypeEnumValues = []UserActionType{
	"PlayedItem",
	"MarkPlayed",
	"MarkFavorite",
}

func (v *UserActionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserActionType(value)
	for _, existing := range AllowedUserActionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserActionType", value)
}

// NewUserActionTypeFromValue returns a pointer to a valid UserActionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserActionTypeFromValue(v string) (*UserActionType, error) {
	ev := UserActionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserActionType: valid values are %v", v, AllowedUserActionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserActionType) IsValid() bool {
	for _, existing := range AllowedUserActionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserActionType value
func (v UserActionType) Ptr() *UserActionType {
	return &v
}

type NullableUserActionType struct {
	value *UserActionType
	isSet bool
}

func (v NullableUserActionType) Get() *UserActionType {
	return v.value
}

func (v *NullableUserActionType) Set(val *UserActionType) {
	v.value = val
	v.isSet = true
}

func (v NullableUserActionType) IsSet() bool {
	return v.isSet
}

func (v *NullableUserActionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserActionType(val *UserActionType) *NullableUserActionType {
	return &NullableUserActionType{value: val, isSet: true}
}

func (v NullableUserActionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserActionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
