/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"fmt"
)

// UserItemShareLevel the model 'UserItemShareLevel'
type UserItemShareLevel string

// List of UserItemShareLevel
const (
	USERITEMSHARELEVEL_NONE UserItemShareLevel = "None"
	USERITEMSHARELEVEL_READ UserItemShareLevel = "Read"
	USERITEMSHARELEVEL_WRITE UserItemShareLevel = "Write"
	USERITEMSHARELEVEL_MANAGE UserItemShareLevel = "Manage"
	USERITEMSHARELEVEL_MANAGE_DELETE UserItemShareLevel = "ManageDelete"
)

// All allowed values of UserItemShareLevel enum
var AllowedUserItemShareLevelEnumValues = []UserItemShareLevel{
	"None",
	"Read",
	"Write",
	"Manage",
	"ManageDelete",
}

func (v *UserItemShareLevel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserItemShareLevel(value)
	for _, existing := range AllowedUserItemShareLevelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserItemShareLevel", value)
}

// NewUserItemShareLevelFromValue returns a pointer to a valid UserItemShareLevel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserItemShareLevelFromValue(v string) (*UserItemShareLevel, error) {
	ev := UserItemShareLevel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserItemShareLevel: valid values are %v", v, AllowedUserItemShareLevelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserItemShareLevel) IsValid() bool {
	for _, existing := range AllowedUserItemShareLevelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserItemShareLevel value
func (v UserItemShareLevel) Ptr() *UserItemShareLevel {
	return &v
}

type NullableUserItemShareLevel struct {
	value *UserItemShareLevel
	isSet bool
}

func (v NullableUserItemShareLevel) Get() *UserItemShareLevel {
	return v.value
}

func (v *NullableUserItemShareLevel) Set(val *UserItemShareLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableUserItemShareLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableUserItemShareLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserItemShareLevel(val *UserItemShareLevel) *NullableUserItemShareLevel {
	return &NullableUserItemShareLevel{value: val, isSet: true}
}

func (v NullableUserItemShareLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserItemShareLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

