/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the LibraryTypeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LibraryTypeOptions{}

// LibraryTypeOptions struct for LibraryTypeOptions
type LibraryTypeOptions struct {
	Type *string `json:"Type,omitempty"`
	MetadataFetchers []LibraryOptionInfo `json:"MetadataFetchers,omitempty"`
	ImageFetchers []LibraryOptionInfo `json:"ImageFetchers,omitempty"`
	SupportedImageTypes []ImageType `json:"SupportedImageTypes,omitempty"`
	DefaultImageOptions []ImageOption `json:"DefaultImageOptions,omitempty"`
}

// NewLibraryTypeOptions instantiates a new LibraryTypeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLibraryTypeOptions() *LibraryTypeOptions {
	this := LibraryTypeOptions{}
	return &this
}

// NewLibraryTypeOptionsWithDefaults instantiates a new LibraryTypeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLibraryTypeOptionsWithDefaults() *LibraryTypeOptions {
	this := LibraryTypeOptions{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *LibraryTypeOptions) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LibraryTypeOptions) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *LibraryTypeOptions) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *LibraryTypeOptions) SetType(v string) {
	o.Type = &v
}

// GetMetadataFetchers returns the MetadataFetchers field value if set, zero value otherwise.
func (o *LibraryTypeOptions) GetMetadataFetchers() []LibraryOptionInfo {
	if o == nil || IsNil(o.MetadataFetchers) {
		var ret []LibraryOptionInfo
		return ret
	}
	return o.MetadataFetchers
}

// GetMetadataFetchersOk returns a tuple with the MetadataFetchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LibraryTypeOptions) GetMetadataFetchersOk() ([]LibraryOptionInfo, bool) {
	if o == nil || IsNil(o.MetadataFetchers) {
		return nil, false
	}
	return o.MetadataFetchers, true
}

// HasMetadataFetchers returns a boolean if a field has been set.
func (o *LibraryTypeOptions) HasMetadataFetchers() bool {
	if o != nil && !IsNil(o.MetadataFetchers) {
		return true
	}

	return false
}

// SetMetadataFetchers gets a reference to the given []LibraryOptionInfo and assigns it to the MetadataFetchers field.
func (o *LibraryTypeOptions) SetMetadataFetchers(v []LibraryOptionInfo) {
	o.MetadataFetchers = v
}

// GetImageFetchers returns the ImageFetchers field value if set, zero value otherwise.
func (o *LibraryTypeOptions) GetImageFetchers() []LibraryOptionInfo {
	if o == nil || IsNil(o.ImageFetchers) {
		var ret []LibraryOptionInfo
		return ret
	}
	return o.ImageFetchers
}

// GetImageFetchersOk returns a tuple with the ImageFetchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LibraryTypeOptions) GetImageFetchersOk() ([]LibraryOptionInfo, bool) {
	if o == nil || IsNil(o.ImageFetchers) {
		return nil, false
	}
	return o.ImageFetchers, true
}

// HasImageFetchers returns a boolean if a field has been set.
func (o *LibraryTypeOptions) HasImageFetchers() bool {
	if o != nil && !IsNil(o.ImageFetchers) {
		return true
	}

	return false
}

// SetImageFetchers gets a reference to the given []LibraryOptionInfo and assigns it to the ImageFetchers field.
func (o *LibraryTypeOptions) SetImageFetchers(v []LibraryOptionInfo) {
	o.ImageFetchers = v
}

// GetSupportedImageTypes returns the SupportedImageTypes field value if set, zero value otherwise.
func (o *LibraryTypeOptions) GetSupportedImageTypes() []ImageType {
	if o == nil || IsNil(o.SupportedImageTypes) {
		var ret []ImageType
		return ret
	}
	return o.SupportedImageTypes
}

// GetSupportedImageTypesOk returns a tuple with the SupportedImageTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LibraryTypeOptions) GetSupportedImageTypesOk() ([]ImageType, bool) {
	if o == nil || IsNil(o.SupportedImageTypes) {
		return nil, false
	}
	return o.SupportedImageTypes, true
}

// HasSupportedImageTypes returns a boolean if a field has been set.
func (o *LibraryTypeOptions) HasSupportedImageTypes() bool {
	if o != nil && !IsNil(o.SupportedImageTypes) {
		return true
	}

	return false
}

// SetSupportedImageTypes gets a reference to the given []ImageType and assigns it to the SupportedImageTypes field.
func (o *LibraryTypeOptions) SetSupportedImageTypes(v []ImageType) {
	o.SupportedImageTypes = v
}

// GetDefaultImageOptions returns the DefaultImageOptions field value if set, zero value otherwise.
func (o *LibraryTypeOptions) GetDefaultImageOptions() []ImageOption {
	if o == nil || IsNil(o.DefaultImageOptions) {
		var ret []ImageOption
		return ret
	}
	return o.DefaultImageOptions
}

// GetDefaultImageOptionsOk returns a tuple with the DefaultImageOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LibraryTypeOptions) GetDefaultImageOptionsOk() ([]ImageOption, bool) {
	if o == nil || IsNil(o.DefaultImageOptions) {
		return nil, false
	}
	return o.DefaultImageOptions, true
}

// HasDefaultImageOptions returns a boolean if a field has been set.
func (o *LibraryTypeOptions) HasDefaultImageOptions() bool {
	if o != nil && !IsNil(o.DefaultImageOptions) {
		return true
	}

	return false
}

// SetDefaultImageOptions gets a reference to the given []ImageOption and assigns it to the DefaultImageOptions field.
func (o *LibraryTypeOptions) SetDefaultImageOptions(v []ImageOption) {
	o.DefaultImageOptions = v
}

func (o LibraryTypeOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LibraryTypeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if !IsNil(o.MetadataFetchers) {
		toSerialize["MetadataFetchers"] = o.MetadataFetchers
	}
	if !IsNil(o.ImageFetchers) {
		toSerialize["ImageFetchers"] = o.ImageFetchers
	}
	if !IsNil(o.SupportedImageTypes) {
		toSerialize["SupportedImageTypes"] = o.SupportedImageTypes
	}
	if !IsNil(o.DefaultImageOptions) {
		toSerialize["DefaultImageOptions"] = o.DefaultImageOptions
	}
	return toSerialize, nil
}

type NullableLibraryTypeOptions struct {
	value *LibraryTypeOptions
	isSet bool
}

func (v NullableLibraryTypeOptions) Get() *LibraryTypeOptions {
	return v.value
}

func (v *NullableLibraryTypeOptions) Set(val *LibraryTypeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableLibraryTypeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableLibraryTypeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLibraryTypeOptions(val *LibraryTypeOptions) *NullableLibraryTypeOptions {
	return &NullableLibraryTypeOptions{value: val, isSet: true}
}

func (v NullableLibraryTypeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLibraryTypeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


