/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"time"
)

// checks if the PlayerStateInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerStateInfo{}

// PlayerStateInfo struct for PlayerStateInfo
type PlayerStateInfo struct {
	PositionTicks       NullableInt64    `json:"PositionTicks,omitempty"`
	CanSeek             *bool            `json:"CanSeek,omitempty"`
	IsPaused            *bool            `json:"IsPaused,omitempty"`
	IsMuted             *bool            `json:"IsMuted,omitempty"`
	VolumeLevel         NullableInt32    `json:"VolumeLevel,omitempty"`
	AudioStreamIndex    NullableInt32    `json:"AudioStreamIndex,omitempty"`
	SubtitleStreamIndex NullableInt32    `json:"SubtitleStreamIndex,omitempty"`
	MediaSourceId       *string          `json:"MediaSourceId,omitempty"`
	MediaSource         *MediaSourceInfo `json:"MediaSource,omitempty"`
	PlayMethod          *PlayMethod      `json:"PlayMethod,omitempty"`
	RepeatMode          *RepeatMode      `json:"RepeatMode,omitempty"`
	SleepTimerMode      *SleepTimerMode  `json:"SleepTimerMode,omitempty"`
	SleepTimerEndTime   NullableTime     `json:"SleepTimerEndTime,omitempty"`
	SubtitleOffset      *int32           `json:"SubtitleOffset,omitempty"`
	Shuffle             *bool            `json:"Shuffle,omitempty"`
	PlaybackRate        *float64         `json:"PlaybackRate,omitempty"`
}

// NewPlayerStateInfo instantiates a new PlayerStateInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerStateInfo() *PlayerStateInfo {
	this := PlayerStateInfo{}
	return &this
}

// NewPlayerStateInfoWithDefaults instantiates a new PlayerStateInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerStateInfoWithDefaults() *PlayerStateInfo {
	this := PlayerStateInfo{}
	return &this
}

// GetPositionTicks returns the PositionTicks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerStateInfo) GetPositionTicks() int64 {
	if o == nil || IsNil(o.PositionTicks.Get()) {
		var ret int64
		return ret
	}
	return *o.PositionTicks.Get()
}

// GetPositionTicksOk returns a tuple with the PositionTicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerStateInfo) GetPositionTicksOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PositionTicks.Get(), o.PositionTicks.IsSet()
}

// HasPositionTicks returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasPositionTicks() bool {
	if o != nil && o.PositionTicks.IsSet() {
		return true
	}

	return false
}

// SetPositionTicks gets a reference to the given NullableInt64 and assigns it to the PositionTicks field.
func (o *PlayerStateInfo) SetPositionTicks(v int64) {
	o.PositionTicks.Set(&v)
}

// SetPositionTicksNil sets the value for PositionTicks to be an explicit nil
func (o *PlayerStateInfo) SetPositionTicksNil() {
	o.PositionTicks.Set(nil)
}

// UnsetPositionTicks ensures that no value is present for PositionTicks, not even an explicit nil
func (o *PlayerStateInfo) UnsetPositionTicks() {
	o.PositionTicks.Unset()
}

// GetCanSeek returns the CanSeek field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetCanSeek() bool {
	if o == nil || IsNil(o.CanSeek) {
		var ret bool
		return ret
	}
	return *o.CanSeek
}

// GetCanSeekOk returns a tuple with the CanSeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetCanSeekOk() (*bool, bool) {
	if o == nil || IsNil(o.CanSeek) {
		return nil, false
	}
	return o.CanSeek, true
}

// HasCanSeek returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasCanSeek() bool {
	if o != nil && !IsNil(o.CanSeek) {
		return true
	}

	return false
}

// SetCanSeek gets a reference to the given bool and assigns it to the CanSeek field.
func (o *PlayerStateInfo) SetCanSeek(v bool) {
	o.CanSeek = &v
}

// GetIsPaused returns the IsPaused field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetIsPaused() bool {
	if o == nil || IsNil(o.IsPaused) {
		var ret bool
		return ret
	}
	return *o.IsPaused
}

// GetIsPausedOk returns a tuple with the IsPaused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetIsPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPaused) {
		return nil, false
	}
	return o.IsPaused, true
}

// HasIsPaused returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasIsPaused() bool {
	if o != nil && !IsNil(o.IsPaused) {
		return true
	}

	return false
}

// SetIsPaused gets a reference to the given bool and assigns it to the IsPaused field.
func (o *PlayerStateInfo) SetIsPaused(v bool) {
	o.IsPaused = &v
}

// GetIsMuted returns the IsMuted field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetIsMuted() bool {
	if o == nil || IsNil(o.IsMuted) {
		var ret bool
		return ret
	}
	return *o.IsMuted
}

// GetIsMutedOk returns a tuple with the IsMuted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetIsMutedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMuted) {
		return nil, false
	}
	return o.IsMuted, true
}

// HasIsMuted returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasIsMuted() bool {
	if o != nil && !IsNil(o.IsMuted) {
		return true
	}

	return false
}

// SetIsMuted gets a reference to the given bool and assigns it to the IsMuted field.
func (o *PlayerStateInfo) SetIsMuted(v bool) {
	o.IsMuted = &v
}

// GetVolumeLevel returns the VolumeLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerStateInfo) GetVolumeLevel() int32 {
	if o == nil || IsNil(o.VolumeLevel.Get()) {
		var ret int32
		return ret
	}
	return *o.VolumeLevel.Get()
}

// GetVolumeLevelOk returns a tuple with the VolumeLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerStateInfo) GetVolumeLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VolumeLevel.Get(), o.VolumeLevel.IsSet()
}

// HasVolumeLevel returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasVolumeLevel() bool {
	if o != nil && o.VolumeLevel.IsSet() {
		return true
	}

	return false
}

// SetVolumeLevel gets a reference to the given NullableInt32 and assigns it to the VolumeLevel field.
func (o *PlayerStateInfo) SetVolumeLevel(v int32) {
	o.VolumeLevel.Set(&v)
}

// SetVolumeLevelNil sets the value for VolumeLevel to be an explicit nil
func (o *PlayerStateInfo) SetVolumeLevelNil() {
	o.VolumeLevel.Set(nil)
}

// UnsetVolumeLevel ensures that no value is present for VolumeLevel, not even an explicit nil
func (o *PlayerStateInfo) UnsetVolumeLevel() {
	o.VolumeLevel.Unset()
}

// GetAudioStreamIndex returns the AudioStreamIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerStateInfo) GetAudioStreamIndex() int32 {
	if o == nil || IsNil(o.AudioStreamIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.AudioStreamIndex.Get()
}

// GetAudioStreamIndexOk returns a tuple with the AudioStreamIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerStateInfo) GetAudioStreamIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AudioStreamIndex.Get(), o.AudioStreamIndex.IsSet()
}

// HasAudioStreamIndex returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasAudioStreamIndex() bool {
	if o != nil && o.AudioStreamIndex.IsSet() {
		return true
	}

	return false
}

// SetAudioStreamIndex gets a reference to the given NullableInt32 and assigns it to the AudioStreamIndex field.
func (o *PlayerStateInfo) SetAudioStreamIndex(v int32) {
	o.AudioStreamIndex.Set(&v)
}

// SetAudioStreamIndexNil sets the value for AudioStreamIndex to be an explicit nil
func (o *PlayerStateInfo) SetAudioStreamIndexNil() {
	o.AudioStreamIndex.Set(nil)
}

// UnsetAudioStreamIndex ensures that no value is present for AudioStreamIndex, not even an explicit nil
func (o *PlayerStateInfo) UnsetAudioStreamIndex() {
	o.AudioStreamIndex.Unset()
}

// GetSubtitleStreamIndex returns the SubtitleStreamIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerStateInfo) GetSubtitleStreamIndex() int32 {
	if o == nil || IsNil(o.SubtitleStreamIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.SubtitleStreamIndex.Get()
}

// GetSubtitleStreamIndexOk returns a tuple with the SubtitleStreamIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerStateInfo) GetSubtitleStreamIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubtitleStreamIndex.Get(), o.SubtitleStreamIndex.IsSet()
}

// HasSubtitleStreamIndex returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasSubtitleStreamIndex() bool {
	if o != nil && o.SubtitleStreamIndex.IsSet() {
		return true
	}

	return false
}

// SetSubtitleStreamIndex gets a reference to the given NullableInt32 and assigns it to the SubtitleStreamIndex field.
func (o *PlayerStateInfo) SetSubtitleStreamIndex(v int32) {
	o.SubtitleStreamIndex.Set(&v)
}

// SetSubtitleStreamIndexNil sets the value for SubtitleStreamIndex to be an explicit nil
func (o *PlayerStateInfo) SetSubtitleStreamIndexNil() {
	o.SubtitleStreamIndex.Set(nil)
}

// UnsetSubtitleStreamIndex ensures that no value is present for SubtitleStreamIndex, not even an explicit nil
func (o *PlayerStateInfo) UnsetSubtitleStreamIndex() {
	o.SubtitleStreamIndex.Unset()
}

// GetMediaSourceId returns the MediaSourceId field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetMediaSourceId() string {
	if o == nil || IsNil(o.MediaSourceId) {
		var ret string
		return ret
	}
	return *o.MediaSourceId
}

// GetMediaSourceIdOk returns a tuple with the MediaSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetMediaSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.MediaSourceId) {
		return nil, false
	}
	return o.MediaSourceId, true
}

// HasMediaSourceId returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasMediaSourceId() bool {
	if o != nil && !IsNil(o.MediaSourceId) {
		return true
	}

	return false
}

// SetMediaSourceId gets a reference to the given string and assigns it to the MediaSourceId field.
func (o *PlayerStateInfo) SetMediaSourceId(v string) {
	o.MediaSourceId = &v
}

// GetMediaSource returns the MediaSource field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetMediaSource() MediaSourceInfo {
	if o == nil || IsNil(o.MediaSource) {
		var ret MediaSourceInfo
		return ret
	}
	return *o.MediaSource
}

// GetMediaSourceOk returns a tuple with the MediaSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetMediaSourceOk() (*MediaSourceInfo, bool) {
	if o == nil || IsNil(o.MediaSource) {
		return nil, false
	}
	return o.MediaSource, true
}

// HasMediaSource returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasMediaSource() bool {
	if o != nil && !IsNil(o.MediaSource) {
		return true
	}

	return false
}

// SetMediaSource gets a reference to the given MediaSourceInfo and assigns it to the MediaSource field.
func (o *PlayerStateInfo) SetMediaSource(v MediaSourceInfo) {
	o.MediaSource = &v
}

// GetPlayMethod returns the PlayMethod field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetPlayMethod() PlayMethod {
	if o == nil || IsNil(o.PlayMethod) {
		var ret PlayMethod
		return ret
	}
	return *o.PlayMethod
}

// GetPlayMethodOk returns a tuple with the PlayMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetPlayMethodOk() (*PlayMethod, bool) {
	if o == nil || IsNil(o.PlayMethod) {
		return nil, false
	}
	return o.PlayMethod, true
}

// HasPlayMethod returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasPlayMethod() bool {
	if o != nil && !IsNil(o.PlayMethod) {
		return true
	}

	return false
}

// SetPlayMethod gets a reference to the given PlayMethod and assigns it to the PlayMethod field.
func (o *PlayerStateInfo) SetPlayMethod(v PlayMethod) {
	o.PlayMethod = &v
}

// GetRepeatMode returns the RepeatMode field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetRepeatMode() RepeatMode {
	if o == nil || IsNil(o.RepeatMode) {
		var ret RepeatMode
		return ret
	}
	return *o.RepeatMode
}

// GetRepeatModeOk returns a tuple with the RepeatMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetRepeatModeOk() (*RepeatMode, bool) {
	if o == nil || IsNil(o.RepeatMode) {
		return nil, false
	}
	return o.RepeatMode, true
}

// HasRepeatMode returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasRepeatMode() bool {
	if o != nil && !IsNil(o.RepeatMode) {
		return true
	}

	return false
}

// SetRepeatMode gets a reference to the given RepeatMode and assigns it to the RepeatMode field.
func (o *PlayerStateInfo) SetRepeatMode(v RepeatMode) {
	o.RepeatMode = &v
}

// GetSleepTimerMode returns the SleepTimerMode field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetSleepTimerMode() SleepTimerMode {
	if o == nil || IsNil(o.SleepTimerMode) {
		var ret SleepTimerMode
		return ret
	}
	return *o.SleepTimerMode
}

// GetSleepTimerModeOk returns a tuple with the SleepTimerMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetSleepTimerModeOk() (*SleepTimerMode, bool) {
	if o == nil || IsNil(o.SleepTimerMode) {
		return nil, false
	}
	return o.SleepTimerMode, true
}

// HasSleepTimerMode returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasSleepTimerMode() bool {
	if o != nil && !IsNil(o.SleepTimerMode) {
		return true
	}

	return false
}

// SetSleepTimerMode gets a reference to the given SleepTimerMode and assigns it to the SleepTimerMode field.
func (o *PlayerStateInfo) SetSleepTimerMode(v SleepTimerMode) {
	o.SleepTimerMode = &v
}

// GetSleepTimerEndTime returns the SleepTimerEndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlayerStateInfo) GetSleepTimerEndTime() time.Time {
	if o == nil || IsNil(o.SleepTimerEndTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SleepTimerEndTime.Get()
}

// GetSleepTimerEndTimeOk returns a tuple with the SleepTimerEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlayerStateInfo) GetSleepTimerEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SleepTimerEndTime.Get(), o.SleepTimerEndTime.IsSet()
}

// HasSleepTimerEndTime returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasSleepTimerEndTime() bool {
	if o != nil && o.SleepTimerEndTime.IsSet() {
		return true
	}

	return false
}

// SetSleepTimerEndTime gets a reference to the given NullableTime and assigns it to the SleepTimerEndTime field.
func (o *PlayerStateInfo) SetSleepTimerEndTime(v time.Time) {
	o.SleepTimerEndTime.Set(&v)
}

// SetSleepTimerEndTimeNil sets the value for SleepTimerEndTime to be an explicit nil
func (o *PlayerStateInfo) SetSleepTimerEndTimeNil() {
	o.SleepTimerEndTime.Set(nil)
}

// UnsetSleepTimerEndTime ensures that no value is present for SleepTimerEndTime, not even an explicit nil
func (o *PlayerStateInfo) UnsetSleepTimerEndTime() {
	o.SleepTimerEndTime.Unset()
}

// GetSubtitleOffset returns the SubtitleOffset field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetSubtitleOffset() int32 {
	if o == nil || IsNil(o.SubtitleOffset) {
		var ret int32
		return ret
	}
	return *o.SubtitleOffset
}

// GetSubtitleOffsetOk returns a tuple with the SubtitleOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetSubtitleOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.SubtitleOffset) {
		return nil, false
	}
	return o.SubtitleOffset, true
}

// HasSubtitleOffset returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasSubtitleOffset() bool {
	if o != nil && !IsNil(o.SubtitleOffset) {
		return true
	}

	return false
}

// SetSubtitleOffset gets a reference to the given int32 and assigns it to the SubtitleOffset field.
func (o *PlayerStateInfo) SetSubtitleOffset(v int32) {
	o.SubtitleOffset = &v
}

// GetShuffle returns the Shuffle field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetShuffle() bool {
	if o == nil || IsNil(o.Shuffle) {
		var ret bool
		return ret
	}
	return *o.Shuffle
}

// GetShuffleOk returns a tuple with the Shuffle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetShuffleOk() (*bool, bool) {
	if o == nil || IsNil(o.Shuffle) {
		return nil, false
	}
	return o.Shuffle, true
}

// HasShuffle returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasShuffle() bool {
	if o != nil && !IsNil(o.Shuffle) {
		return true
	}

	return false
}

// SetShuffle gets a reference to the given bool and assigns it to the Shuffle field.
func (o *PlayerStateInfo) SetShuffle(v bool) {
	o.Shuffle = &v
}

// GetPlaybackRate returns the PlaybackRate field value if set, zero value otherwise.
func (o *PlayerStateInfo) GetPlaybackRate() float64 {
	if o == nil || IsNil(o.PlaybackRate) {
		var ret float64
		return ret
	}
	return *o.PlaybackRate
}

// GetPlaybackRateOk returns a tuple with the PlaybackRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerStateInfo) GetPlaybackRateOk() (*float64, bool) {
	if o == nil || IsNil(o.PlaybackRate) {
		return nil, false
	}
	return o.PlaybackRate, true
}

// HasPlaybackRate returns a boolean if a field has been set.
func (o *PlayerStateInfo) HasPlaybackRate() bool {
	if o != nil && !IsNil(o.PlaybackRate) {
		return true
	}

	return false
}

// SetPlaybackRate gets a reference to the given float64 and assigns it to the PlaybackRate field.
func (o *PlayerStateInfo) SetPlaybackRate(v float64) {
	o.PlaybackRate = &v
}

func (o PlayerStateInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerStateInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PositionTicks.IsSet() {
		toSerialize["PositionTicks"] = o.PositionTicks.Get()
	}
	if !IsNil(o.CanSeek) {
		toSerialize["CanSeek"] = o.CanSeek
	}
	if !IsNil(o.IsPaused) {
		toSerialize["IsPaused"] = o.IsPaused
	}
	if !IsNil(o.IsMuted) {
		toSerialize["IsMuted"] = o.IsMuted
	}
	if o.VolumeLevel.IsSet() {
		toSerialize["VolumeLevel"] = o.VolumeLevel.Get()
	}
	if o.AudioStreamIndex.IsSet() {
		toSerialize["AudioStreamIndex"] = o.AudioStreamIndex.Get()
	}
	if o.SubtitleStreamIndex.IsSet() {
		toSerialize["SubtitleStreamIndex"] = o.SubtitleStreamIndex.Get()
	}
	if !IsNil(o.MediaSourceId) {
		toSerialize["MediaSourceId"] = o.MediaSourceId
	}
	if !IsNil(o.MediaSource) {
		toSerialize["MediaSource"] = o.MediaSource
	}
	if !IsNil(o.PlayMethod) {
		toSerialize["PlayMethod"] = o.PlayMethod
	}
	if !IsNil(o.RepeatMode) {
		toSerialize["RepeatMode"] = o.RepeatMode
	}
	if !IsNil(o.SleepTimerMode) {
		toSerialize["SleepTimerMode"] = o.SleepTimerMode
	}
	if o.SleepTimerEndTime.IsSet() {
		toSerialize["SleepTimerEndTime"] = o.SleepTimerEndTime.Get()
	}
	if !IsNil(o.SubtitleOffset) {
		toSerialize["SubtitleOffset"] = o.SubtitleOffset
	}
	if !IsNil(o.Shuffle) {
		toSerialize["Shuffle"] = o.Shuffle
	}
	if !IsNil(o.PlaybackRate) {
		toSerialize["PlaybackRate"] = o.PlaybackRate
	}
	return toSerialize, nil
}

type NullablePlayerStateInfo struct {
	value *PlayerStateInfo
	isSet bool
}

func (v NullablePlayerStateInfo) Get() *PlayerStateInfo {
	return v.value
}

func (v *NullablePlayerStateInfo) Set(val *PlayerStateInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerStateInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerStateInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerStateInfo(val *PlayerStateInfo) *NullablePlayerStateInfo {
	return &NullablePlayerStateInfo{value: val, isSet: true}
}

func (v NullablePlayerStateInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerStateInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
