/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the LiveTvKeywordInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LiveTvKeywordInfo{}

// LiveTvKeywordInfo struct for LiveTvKeywordInfo
type LiveTvKeywordInfo struct {
	KeywordType *LiveTvKeywordType `json:"KeywordType,omitempty"`
	Keyword *string `json:"Keyword,omitempty"`
}

// NewLiveTvKeywordInfo instantiates a new LiveTvKeywordInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveTvKeywordInfo() *LiveTvKeywordInfo {
	this := LiveTvKeywordInfo{}
	return &this
}

// NewLiveTvKeywordInfoWithDefaults instantiates a new LiveTvKeywordInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveTvKeywordInfoWithDefaults() *LiveTvKeywordInfo {
	this := LiveTvKeywordInfo{}
	return &this
}

// GetKeywordType returns the KeywordType field value if set, zero value otherwise.
func (o *LiveTvKeywordInfo) GetKeywordType() LiveTvKeywordType {
	if o == nil || IsNil(o.KeywordType) {
		var ret LiveTvKeywordType
		return ret
	}
	return *o.KeywordType
}

// GetKeywordTypeOk returns a tuple with the KeywordType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveTvKeywordInfo) GetKeywordTypeOk() (*LiveTvKeywordType, bool) {
	if o == nil || IsNil(o.KeywordType) {
		return nil, false
	}
	return o.KeywordType, true
}

// HasKeywordType returns a boolean if a field has been set.
func (o *LiveTvKeywordInfo) HasKeywordType() bool {
	if o != nil && !IsNil(o.KeywordType) {
		return true
	}

	return false
}

// SetKeywordType gets a reference to the given LiveTvKeywordType and assigns it to the KeywordType field.
func (o *LiveTvKeywordInfo) SetKeywordType(v LiveTvKeywordType) {
	o.KeywordType = &v
}

// GetKeyword returns the Keyword field value if set, zero value otherwise.
func (o *LiveTvKeywordInfo) GetKeyword() string {
	if o == nil || IsNil(o.Keyword) {
		var ret string
		return ret
	}
	return *o.Keyword
}

// GetKeywordOk returns a tuple with the Keyword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveTvKeywordInfo) GetKeywordOk() (*string, bool) {
	if o == nil || IsNil(o.Keyword) {
		return nil, false
	}
	return o.Keyword, true
}

// HasKeyword returns a boolean if a field has been set.
func (o *LiveTvKeywordInfo) HasKeyword() bool {
	if o != nil && !IsNil(o.Keyword) {
		return true
	}

	return false
}

// SetKeyword gets a reference to the given string and assigns it to the Keyword field.
func (o *LiveTvKeywordInfo) SetKeyword(v string) {
	o.Keyword = &v
}

func (o LiveTvKeywordInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LiveTvKeywordInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeywordType) {
		toSerialize["KeywordType"] = o.KeywordType
	}
	if !IsNil(o.Keyword) {
		toSerialize["Keyword"] = o.Keyword
	}
	return toSerialize, nil
}

type NullableLiveTvKeywordInfo struct {
	value *LiveTvKeywordInfo
	isSet bool
}

func (v NullableLiveTvKeywordInfo) Get() *LiveTvKeywordInfo {
	return v.value
}

func (v *NullableLiveTvKeywordInfo) Set(val *LiveTvKeywordInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveTvKeywordInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveTvKeywordInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveTvKeywordInfo(val *LiveTvKeywordInfo) *NullableLiveTvKeywordInfo {
	return &NullableLiveTvKeywordInfo{value: val, isSet: true}
}

func (v NullableLiveTvKeywordInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiveTvKeywordInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


