/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the SubtitleProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubtitleProfile{}

// SubtitleProfile struct for SubtitleProfile
type SubtitleProfile struct {
	Format               *string                 `json:"Format,omitempty"`
	Method               *SubtitleDeliveryMethod `json:"Method,omitempty"`
	DidlMode             *string                 `json:"DidlMode,omitempty"`
	Language             *string                 `json:"Language,omitempty"`
	Container            *string                 `json:"Container,omitempty"`
	AllowChunkedResponse *bool                   `json:"AllowChunkedResponse,omitempty"`
	Protocol             *string                 `json:"Protocol,omitempty"`
}

// NewSubtitleProfile instantiates a new SubtitleProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubtitleProfile() *SubtitleProfile {
	this := SubtitleProfile{}
	return &this
}

// NewSubtitleProfileWithDefaults instantiates a new SubtitleProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubtitleProfileWithDefaults() *SubtitleProfile {
	this := SubtitleProfile{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *SubtitleProfile) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *SubtitleProfile) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *SubtitleProfile) SetFormat(v string) {
	o.Format = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *SubtitleProfile) GetMethod() SubtitleDeliveryMethod {
	if o == nil || IsNil(o.Method) {
		var ret SubtitleDeliveryMethod
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetMethodOk() (*SubtitleDeliveryMethod, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *SubtitleProfile) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given SubtitleDeliveryMethod and assigns it to the Method field.
func (o *SubtitleProfile) SetMethod(v SubtitleDeliveryMethod) {
	o.Method = &v
}

// GetDidlMode returns the DidlMode field value if set, zero value otherwise.
func (o *SubtitleProfile) GetDidlMode() string {
	if o == nil || IsNil(o.DidlMode) {
		var ret string
		return ret
	}
	return *o.DidlMode
}

// GetDidlModeOk returns a tuple with the DidlMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetDidlModeOk() (*string, bool) {
	if o == nil || IsNil(o.DidlMode) {
		return nil, false
	}
	return o.DidlMode, true
}

// HasDidlMode returns a boolean if a field has been set.
func (o *SubtitleProfile) HasDidlMode() bool {
	if o != nil && !IsNil(o.DidlMode) {
		return true
	}

	return false
}

// SetDidlMode gets a reference to the given string and assigns it to the DidlMode field.
func (o *SubtitleProfile) SetDidlMode(v string) {
	o.DidlMode = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *SubtitleProfile) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *SubtitleProfile) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *SubtitleProfile) SetLanguage(v string) {
	o.Language = &v
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *SubtitleProfile) GetContainer() string {
	if o == nil || IsNil(o.Container) {
		var ret string
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetContainerOk() (*string, bool) {
	if o == nil || IsNil(o.Container) {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *SubtitleProfile) HasContainer() bool {
	if o != nil && !IsNil(o.Container) {
		return true
	}

	return false
}

// SetContainer gets a reference to the given string and assigns it to the Container field.
func (o *SubtitleProfile) SetContainer(v string) {
	o.Container = &v
}

// GetAllowChunkedResponse returns the AllowChunkedResponse field value if set, zero value otherwise.
func (o *SubtitleProfile) GetAllowChunkedResponse() bool {
	if o == nil || IsNil(o.AllowChunkedResponse) {
		var ret bool
		return ret
	}
	return *o.AllowChunkedResponse
}

// GetAllowChunkedResponseOk returns a tuple with the AllowChunkedResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetAllowChunkedResponseOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowChunkedResponse) {
		return nil, false
	}
	return o.AllowChunkedResponse, true
}

// HasAllowChunkedResponse returns a boolean if a field has been set.
func (o *SubtitleProfile) HasAllowChunkedResponse() bool {
	if o != nil && !IsNil(o.AllowChunkedResponse) {
		return true
	}

	return false
}

// SetAllowChunkedResponse gets a reference to the given bool and assigns it to the AllowChunkedResponse field.
func (o *SubtitleProfile) SetAllowChunkedResponse(v bool) {
	o.AllowChunkedResponse = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *SubtitleProfile) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubtitleProfile) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *SubtitleProfile) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *SubtitleProfile) SetProtocol(v string) {
	o.Protocol = &v
}

func (o SubtitleProfile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubtitleProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["Format"] = o.Format
	}
	if !IsNil(o.Method) {
		toSerialize["Method"] = o.Method
	}
	if !IsNil(o.DidlMode) {
		toSerialize["DidlMode"] = o.DidlMode
	}
	if !IsNil(o.Language) {
		toSerialize["Language"] = o.Language
	}
	if !IsNil(o.Container) {
		toSerialize["Container"] = o.Container
	}
	if !IsNil(o.AllowChunkedResponse) {
		toSerialize["AllowChunkedResponse"] = o.AllowChunkedResponse
	}
	if !IsNil(o.Protocol) {
		toSerialize["Protocol"] = o.Protocol
	}
	return toSerialize, nil
}

type NullableSubtitleProfile struct {
	value *SubtitleProfile
	isSet bool
}

func (v NullableSubtitleProfile) Get() *SubtitleProfile {
	return v.value
}

func (v *NullableSubtitleProfile) Set(val *SubtitleProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableSubtitleProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableSubtitleProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubtitleProfile(val *SubtitleProfile) *NullableSubtitleProfile {
	return &NullableSubtitleProfile{value: val, isSet: true}
}

func (v NullableSubtitleProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubtitleProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
