/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the SyncedItemProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncedItemProgress{}

// SyncedItemProgress struct for SyncedItemProgress
type SyncedItemProgress struct {
	Progress NullableFloat64 `json:"Progress,omitempty"`
	Status *SyncJobItemStatus `json:"Status,omitempty"`
}

// NewSyncedItemProgress instantiates a new SyncedItemProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncedItemProgress() *SyncedItemProgress {
	this := SyncedItemProgress{}
	return &this
}

// NewSyncedItemProgressWithDefaults instantiates a new SyncedItemProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncedItemProgressWithDefaults() *SyncedItemProgress {
	this := SyncedItemProgress{}
	return &this
}

// GetProgress returns the Progress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SyncedItemProgress) GetProgress() float64 {
	if o == nil || IsNil(o.Progress.Get()) {
		var ret float64
		return ret
	}
	return *o.Progress.Get()
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SyncedItemProgress) GetProgressOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Progress.Get(), o.Progress.IsSet()
}

// HasProgress returns a boolean if a field has been set.
func (o *SyncedItemProgress) HasProgress() bool {
	if o != nil && o.Progress.IsSet() {
		return true
	}

	return false
}

// SetProgress gets a reference to the given NullableFloat64 and assigns it to the Progress field.
func (o *SyncedItemProgress) SetProgress(v float64) {
	o.Progress.Set(&v)
}
// SetProgressNil sets the value for Progress to be an explicit nil
func (o *SyncedItemProgress) SetProgressNil() {
	o.Progress.Set(nil)
}

// UnsetProgress ensures that no value is present for Progress, not even an explicit nil
func (o *SyncedItemProgress) UnsetProgress() {
	o.Progress.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SyncedItemProgress) GetStatus() SyncJobItemStatus {
	if o == nil || IsNil(o.Status) {
		var ret SyncJobItemStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncedItemProgress) GetStatusOk() (*SyncJobItemStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SyncedItemProgress) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given SyncJobItemStatus and assigns it to the Status field.
func (o *SyncedItemProgress) SetStatus(v SyncJobItemStatus) {
	o.Status = &v
}

func (o SyncedItemProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncedItemProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Progress.IsSet() {
		toSerialize["Progress"] = o.Progress.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["Status"] = o.Status
	}
	return toSerialize, nil
}

type NullableSyncedItemProgress struct {
	value *SyncedItemProgress
	isSet bool
}

func (v NullableSyncedItemProgress) Get() *SyncedItemProgress {
	return v.value
}

func (v *NullableSyncedItemProgress) Set(val *SyncedItemProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncedItemProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncedItemProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncedItemProgress(val *SyncedItemProgress) *NullableSyncedItemProgress {
	return &NullableSyncedItemProgress{value: val, isSet: true}
}

func (v NullableSyncedItemProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncedItemProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


