/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"fmt"
)

// SubtitleLocationType the model 'SubtitleLocationType'
type SubtitleLocationType string

// List of SubtitleLocationType
const (
	SUBTITLELOCATIONTYPE_INTERNAL_STREAM SubtitleLocationType = "InternalStream"
	SUBTITLELOCATIONTYPE_VIDEO_SIDE_DATA SubtitleLocationType = "VideoSideData"
)

// All allowed values of SubtitleLocationType enum
var AllowedSubtitleLocationTypeEnumValues = []SubtitleLocationType{
	"InternalStream",
	"VideoSideData",
}

func (v *SubtitleLocationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SubtitleLocationType(value)
	for _, existing := range AllowedSubtitleLocationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SubtitleLocationType", value)
}

// NewSubtitleLocationTypeFromValue returns a pointer to a valid SubtitleLocationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSubtitleLocationTypeFromValue(v string) (*SubtitleLocationType, error) {
	ev := SubtitleLocationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SubtitleLocationType: valid values are %v", v, AllowedSubtitleLocationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SubtitleLocationType) IsValid() bool {
	for _, existing := range AllowedSubtitleLocationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SubtitleLocationType value
func (v SubtitleLocationType) Ptr() *SubtitleLocationType {
	return &v
}

type NullableSubtitleLocationType struct {
	value *SubtitleLocationType
	isSet bool
}

func (v NullableSubtitleLocationType) Get() *SubtitleLocationType {
	return v.value
}

func (v *NullableSubtitleLocationType) Set(val *SubtitleLocationType) {
	v.value = val
	v.isSet = true
}

func (v NullableSubtitleLocationType) IsSet() bool {
	return v.isSet
}

func (v *NullableSubtitleLocationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubtitleLocationType(val *SubtitleLocationType) *NullableSubtitleLocationType {
	return &NullableSubtitleLocationType{value: val, isSet: true}
}

func (v NullableSubtitleLocationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubtitleLocationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
