/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"fmt"
)

// ProxyHeaderMode the model 'ProxyHeaderMode'
type ProxyHeaderMode string

// List of ProxyHeaderMode
const (
	PROXYHEADERMODE_NONE ProxyHeaderMode = "None"
	PROXYHEADERMODE_LAN_ADDRESSES_ONLY ProxyHeaderMode = "LanAddressesOnly"
	PROXYHEADERMODE_REMOTE_ADDRESSES_ONLY ProxyHeaderMode = "RemoteAddressesOnly"
	PROXYHEADERMODE_ALL_ADDRESSES ProxyHeaderMode = "AllAddresses"
)

// All allowed values of ProxyHeaderMode enum
var AllowedProxyHeaderModeEnumValues = []ProxyHeaderMode{
	"None",
	"LanAddressesOnly",
	"RemoteAddressesOnly",
	"AllAddresses",
}

func (v *ProxyHeaderMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProxyHeaderMode(value)
	for _, existing := range AllowedProxyHeaderModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProxyHeaderMode", value)
}

// NewProxyHeaderModeFromValue returns a pointer to a valid ProxyHeaderMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProxyHeaderModeFromValue(v string) (*ProxyHeaderMode, error) {
	ev := ProxyHeaderMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProxyHeaderMode: valid values are %v", v, AllowedProxyHeaderModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProxyHeaderMode) IsValid() bool {
	for _, existing := range AllowedProxyHeaderModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProxyHeaderMode value
func (v ProxyHeaderMode) Ptr() *ProxyHeaderMode {
	return &v
}

type NullableProxyHeaderMode struct {
	value *ProxyHeaderMode
	isSet bool
}

func (v NullableProxyHeaderMode) Get() *ProxyHeaderMode {
	return v.value
}

func (v *NullableProxyHeaderMode) Set(val *ProxyHeaderMode) {
	v.value = val
	v.isSet = true
}

func (v NullableProxyHeaderMode) IsSet() bool {
	return v.isSet
}

func (v *NullableProxyHeaderMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxyHeaderMode(val *ProxyHeaderMode) *NullableProxyHeaderMode {
	return &NullableProxyHeaderMode{value: val, isSet: true}
}

func (v NullableProxyHeaderMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxyHeaderMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

