/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the ProcessRunMetricsProcessMetricPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessRunMetricsProcessMetricPoint{}

// ProcessRunMetricsProcessMetricPoint struct for ProcessRunMetricsProcessMetricPoint
type ProcessRunMetricsProcessMetricPoint struct {
	Time *string `json:"Time,omitempty"`
	CpuPercent *float64 `json:"CpuPercent,omitempty"`
	VirtualMemory *float64 `json:"VirtualMemory,omitempty"`
	WorkingSet *float64 `json:"WorkingSet,omitempty"`
}

// NewProcessRunMetricsProcessMetricPoint instantiates a new ProcessRunMetricsProcessMetricPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessRunMetricsProcessMetricPoint() *ProcessRunMetricsProcessMetricPoint {
	this := ProcessRunMetricsProcessMetricPoint{}
	return &this
}

// NewProcessRunMetricsProcessMetricPointWithDefaults instantiates a new ProcessRunMetricsProcessMetricPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessRunMetricsProcessMetricPointWithDefaults() *ProcessRunMetricsProcessMetricPoint {
	this := ProcessRunMetricsProcessMetricPoint{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ProcessRunMetricsProcessMetricPoint) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessRunMetricsProcessMetricPoint) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ProcessRunMetricsProcessMetricPoint) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *ProcessRunMetricsProcessMetricPoint) SetTime(v string) {
	o.Time = &v
}

// GetCpuPercent returns the CpuPercent field value if set, zero value otherwise.
func (o *ProcessRunMetricsProcessMetricPoint) GetCpuPercent() float64 {
	if o == nil || IsNil(o.CpuPercent) {
		var ret float64
		return ret
	}
	return *o.CpuPercent
}

// GetCpuPercentOk returns a tuple with the CpuPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessRunMetricsProcessMetricPoint) GetCpuPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.CpuPercent) {
		return nil, false
	}
	return o.CpuPercent, true
}

// HasCpuPercent returns a boolean if a field has been set.
func (o *ProcessRunMetricsProcessMetricPoint) HasCpuPercent() bool {
	if o != nil && !IsNil(o.CpuPercent) {
		return true
	}

	return false
}

// SetCpuPercent gets a reference to the given float64 and assigns it to the CpuPercent field.
func (o *ProcessRunMetricsProcessMetricPoint) SetCpuPercent(v float64) {
	o.CpuPercent = &v
}

// GetVirtualMemory returns the VirtualMemory field value if set, zero value otherwise.
func (o *ProcessRunMetricsProcessMetricPoint) GetVirtualMemory() float64 {
	if o == nil || IsNil(o.VirtualMemory) {
		var ret float64
		return ret
	}
	return *o.VirtualMemory
}

// GetVirtualMemoryOk returns a tuple with the VirtualMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessRunMetricsProcessMetricPoint) GetVirtualMemoryOk() (*float64, bool) {
	if o == nil || IsNil(o.VirtualMemory) {
		return nil, false
	}
	return o.VirtualMemory, true
}

// HasVirtualMemory returns a boolean if a field has been set.
func (o *ProcessRunMetricsProcessMetricPoint) HasVirtualMemory() bool {
	if o != nil && !IsNil(o.VirtualMemory) {
		return true
	}

	return false
}

// SetVirtualMemory gets a reference to the given float64 and assigns it to the VirtualMemory field.
func (o *ProcessRunMetricsProcessMetricPoint) SetVirtualMemory(v float64) {
	o.VirtualMemory = &v
}

// GetWorkingSet returns the WorkingSet field value if set, zero value otherwise.
func (o *ProcessRunMetricsProcessMetricPoint) GetWorkingSet() float64 {
	if o == nil || IsNil(o.WorkingSet) {
		var ret float64
		return ret
	}
	return *o.WorkingSet
}

// GetWorkingSetOk returns a tuple with the WorkingSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessRunMetricsProcessMetricPoint) GetWorkingSetOk() (*float64, bool) {
	if o == nil || IsNil(o.WorkingSet) {
		return nil, false
	}
	return o.WorkingSet, true
}

// HasWorkingSet returns a boolean if a field has been set.
func (o *ProcessRunMetricsProcessMetricPoint) HasWorkingSet() bool {
	if o != nil && !IsNil(o.WorkingSet) {
		return true
	}

	return false
}

// SetWorkingSet gets a reference to the given float64 and assigns it to the WorkingSet field.
func (o *ProcessRunMetricsProcessMetricPoint) SetWorkingSet(v float64) {
	o.WorkingSet = &v
}

func (o ProcessRunMetricsProcessMetricPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessRunMetricsProcessMetricPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Time) {
		toSerialize["Time"] = o.Time
	}
	if !IsNil(o.CpuPercent) {
		toSerialize["CpuPercent"] = o.CpuPercent
	}
	if !IsNil(o.VirtualMemory) {
		toSerialize["VirtualMemory"] = o.VirtualMemory
	}
	if !IsNil(o.WorkingSet) {
		toSerialize["WorkingSet"] = o.WorkingSet
	}
	return toSerialize, nil
}

type NullableProcessRunMetricsProcessMetricPoint struct {
	value *ProcessRunMetricsProcessMetricPoint
	isSet bool
}

func (v NullableProcessRunMetricsProcessMetricPoint) Get() *ProcessRunMetricsProcessMetricPoint {
	return v.value
}

func (v *NullableProcessRunMetricsProcessMetricPoint) Set(val *ProcessRunMetricsProcessMetricPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessRunMetricsProcessMetricPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessRunMetricsProcessMetricPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessRunMetricsProcessMetricPoint(val *ProcessRunMetricsProcessMetricPoint) *NullableProcessRunMetricsProcessMetricPoint {
	return &NullableProcessRunMetricsProcessMetricPoint{value: val, isSet: true}
}

func (v NullableProcessRunMetricsProcessMetricPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessRunMetricsProcessMetricPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


