/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the UserLibraryUpdateUserItemAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserLibraryUpdateUserItemAccess{}

// UserLibraryUpdateUserItemAccess struct for UserLibraryUpdateUserItemAccess
type UserLibraryUpdateUserItemAccess struct {
	ItemIds []string `json:"ItemIds,omitempty"`
	UserIds []string `json:"UserIds,omitempty"`
	ItemAccess *UserItemShareLevel `json:"ItemAccess,omitempty"`
}

// NewUserLibraryUpdateUserItemAccess instantiates a new UserLibraryUpdateUserItemAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserLibraryUpdateUserItemAccess() *UserLibraryUpdateUserItemAccess {
	this := UserLibraryUpdateUserItemAccess{}
	return &this
}

// NewUserLibraryUpdateUserItemAccessWithDefaults instantiates a new UserLibraryUpdateUserItemAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserLibraryUpdateUserItemAccessWithDefaults() *UserLibraryUpdateUserItemAccess {
	this := UserLibraryUpdateUserItemAccess{}
	return &this
}

// GetItemIds returns the ItemIds field value if set, zero value otherwise.
func (o *UserLibraryUpdateUserItemAccess) GetItemIds() []string {
	if o == nil || IsNil(o.ItemIds) {
		var ret []string
		return ret
	}
	return o.ItemIds
}

// GetItemIdsOk returns a tuple with the ItemIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLibraryUpdateUserItemAccess) GetItemIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ItemIds) {
		return nil, false
	}
	return o.ItemIds, true
}

// HasItemIds returns a boolean if a field has been set.
func (o *UserLibraryUpdateUserItemAccess) HasItemIds() bool {
	if o != nil && !IsNil(o.ItemIds) {
		return true
	}

	return false
}

// SetItemIds gets a reference to the given []string and assigns it to the ItemIds field.
func (o *UserLibraryUpdateUserItemAccess) SetItemIds(v []string) {
	o.ItemIds = v
}

// GetUserIds returns the UserIds field value if set, zero value otherwise.
func (o *UserLibraryUpdateUserItemAccess) GetUserIds() []string {
	if o == nil || IsNil(o.UserIds) {
		var ret []string
		return ret
	}
	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLibraryUpdateUserItemAccess) GetUserIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.UserIds) {
		return nil, false
	}
	return o.UserIds, true
}

// HasUserIds returns a boolean if a field has been set.
func (o *UserLibraryUpdateUserItemAccess) HasUserIds() bool {
	if o != nil && !IsNil(o.UserIds) {
		return true
	}

	return false
}

// SetUserIds gets a reference to the given []string and assigns it to the UserIds field.
func (o *UserLibraryUpdateUserItemAccess) SetUserIds(v []string) {
	o.UserIds = v
}

// GetItemAccess returns the ItemAccess field value if set, zero value otherwise.
func (o *UserLibraryUpdateUserItemAccess) GetItemAccess() UserItemShareLevel {
	if o == nil || IsNil(o.ItemAccess) {
		var ret UserItemShareLevel
		return ret
	}
	return *o.ItemAccess
}

// GetItemAccessOk returns a tuple with the ItemAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLibraryUpdateUserItemAccess) GetItemAccessOk() (*UserItemShareLevel, bool) {
	if o == nil || IsNil(o.ItemAccess) {
		return nil, false
	}
	return o.ItemAccess, true
}

// HasItemAccess returns a boolean if a field has been set.
func (o *UserLibraryUpdateUserItemAccess) HasItemAccess() bool {
	if o != nil && !IsNil(o.ItemAccess) {
		return true
	}

	return false
}

// SetItemAccess gets a reference to the given UserItemShareLevel and assigns it to the ItemAccess field.
func (o *UserLibraryUpdateUserItemAccess) SetItemAccess(v UserItemShareLevel) {
	o.ItemAccess = &v
}

func (o UserLibraryUpdateUserItemAccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserLibraryUpdateUserItemAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ItemIds) {
		toSerialize["ItemIds"] = o.ItemIds
	}
	if !IsNil(o.UserIds) {
		toSerialize["UserIds"] = o.UserIds
	}
	if !IsNil(o.ItemAccess) {
		toSerialize["ItemAccess"] = o.ItemAccess
	}
	return toSerialize, nil
}

type NullableUserLibraryUpdateUserItemAccess struct {
	value *UserLibraryUpdateUserItemAccess
	isSet bool
}

func (v NullableUserLibraryUpdateUserItemAccess) Get() *UserLibraryUpdateUserItemAccess {
	return v.value
}

func (v *NullableUserLibraryUpdateUserItemAccess) Set(val *UserLibraryUpdateUserItemAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableUserLibraryUpdateUserItemAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableUserLibraryUpdateUserItemAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserLibraryUpdateUserItemAccess(val *UserLibraryUpdateUserItemAccess) *NullableUserLibraryUpdateUserItemAccess {
	return &NullableUserLibraryUpdateUserItemAccess{value: val, isSet: true}
}

func (v NullableUserLibraryUpdateUserItemAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserLibraryUpdateUserItemAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


