/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"fmt"
)

// MetadataFeatures the model 'MetadataFeatures'
type MetadataFeatures string

// List of MetadataFeatures
const (
	METADATAFEATURES_COLLECTIONS    MetadataFeatures = "Collections"
	METADATAFEATURES_ADULT          MetadataFeatures = "Adult"
	METADATAFEATURES_REQUIRED_SETUP MetadataFeatures = "RequiredSetup"
)

// All allowed values of MetadataFeatures enum
var AllowedMetadataFeaturesEnumValues = []MetadataFeatures{
	"Collections",
	"Adult",
	"RequiredSetup",
}

func (v *MetadataFeatures) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MetadataFeatures(value)
	for _, existing := range AllowedMetadataFeaturesEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MetadataFeatures", value)
}

// NewMetadataFeaturesFromValue returns a pointer to a valid MetadataFeatures
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMetadataFeaturesFromValue(v string) (*MetadataFeatures, error) {
	ev := MetadataFeatures(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MetadataFeatures: valid values are %v", v, AllowedMetadataFeaturesEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MetadataFeatures) IsValid() bool {
	for _, existing := range AllowedMetadataFeaturesEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MetadataFeatures value
func (v MetadataFeatures) Ptr() *MetadataFeatures {
	return &v
}

type NullableMetadataFeatures struct {
	value *MetadataFeatures
	isSet bool
}

func (v NullableMetadataFeatures) Get() *MetadataFeatures {
	return v.value
}

func (v *NullableMetadataFeatures) Set(val *MetadataFeatures) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataFeatures) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataFeatures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataFeatures(val *MetadataFeatures) *NullableMetadataFeatures {
	return &NullableMetadataFeatures{value: val, isSet: true}
}

func (v NullableMetadataFeatures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataFeatures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
