/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
	"time"
)

// checks if the EntitiesItemImageInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitiesItemImageInfo{}

// EntitiesItemImageInfo struct for EntitiesItemImageInfo
type EntitiesItemImageInfo struct {
	Path *string `json:"Path,omitempty"`
	Type *ImageType `json:"Type,omitempty"`
	Orientation *DrawingImageOrientation `json:"Orientation,omitempty"`
	DateModified *time.Time `json:"DateModified,omitempty"`
	Width *int32 `json:"Width,omitempty"`
	Height *int32 `json:"Height,omitempty"`
}

// NewEntitiesItemImageInfo instantiates a new EntitiesItemImageInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitiesItemImageInfo() *EntitiesItemImageInfo {
	this := EntitiesItemImageInfo{}
	return &this
}

// NewEntitiesItemImageInfoWithDefaults instantiates a new EntitiesItemImageInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitiesItemImageInfoWithDefaults() *EntitiesItemImageInfo {
	this := EntitiesItemImageInfo{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *EntitiesItemImageInfo) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesItemImageInfo) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *EntitiesItemImageInfo) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *EntitiesItemImageInfo) SetPath(v string) {
	o.Path = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EntitiesItemImageInfo) GetType() ImageType {
	if o == nil || IsNil(o.Type) {
		var ret ImageType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesItemImageInfo) GetTypeOk() (*ImageType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EntitiesItemImageInfo) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given ImageType and assigns it to the Type field.
func (o *EntitiesItemImageInfo) SetType(v ImageType) {
	o.Type = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *EntitiesItemImageInfo) GetOrientation() DrawingImageOrientation {
	if o == nil || IsNil(o.Orientation) {
		var ret DrawingImageOrientation
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesItemImageInfo) GetOrientationOk() (*DrawingImageOrientation, bool) {
	if o == nil || IsNil(o.Orientation) {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *EntitiesItemImageInfo) HasOrientation() bool {
	if o != nil && !IsNil(o.Orientation) {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given DrawingImageOrientation and assigns it to the Orientation field.
func (o *EntitiesItemImageInfo) SetOrientation(v DrawingImageOrientation) {
	o.Orientation = &v
}

// GetDateModified returns the DateModified field value if set, zero value otherwise.
func (o *EntitiesItemImageInfo) GetDateModified() time.Time {
	if o == nil || IsNil(o.DateModified) {
		var ret time.Time
		return ret
	}
	return *o.DateModified
}

// GetDateModifiedOk returns a tuple with the DateModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesItemImageInfo) GetDateModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateModified) {
		return nil, false
	}
	return o.DateModified, true
}

// HasDateModified returns a boolean if a field has been set.
func (o *EntitiesItemImageInfo) HasDateModified() bool {
	if o != nil && !IsNil(o.DateModified) {
		return true
	}

	return false
}

// SetDateModified gets a reference to the given time.Time and assigns it to the DateModified field.
func (o *EntitiesItemImageInfo) SetDateModified(v time.Time) {
	o.DateModified = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *EntitiesItemImageInfo) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesItemImageInfo) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *EntitiesItemImageInfo) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *EntitiesItemImageInfo) SetWidth(v int32) {
	o.Width = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *EntitiesItemImageInfo) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntitiesItemImageInfo) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *EntitiesItemImageInfo) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *EntitiesItemImageInfo) SetHeight(v int32) {
	o.Height = &v
}

func (o EntitiesItemImageInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntitiesItemImageInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["Path"] = o.Path
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if !IsNil(o.Orientation) {
		toSerialize["Orientation"] = o.Orientation
	}
	if !IsNil(o.DateModified) {
		toSerialize["DateModified"] = o.DateModified
	}
	if !IsNil(o.Width) {
		toSerialize["Width"] = o.Width
	}
	if !IsNil(o.Height) {
		toSerialize["Height"] = o.Height
	}
	return toSerialize, nil
}

type NullableEntitiesItemImageInfo struct {
	value *EntitiesItemImageInfo
	isSet bool
}

func (v NullableEntitiesItemImageInfo) Get() *EntitiesItemImageInfo {
	return v.value
}

func (v *NullableEntitiesItemImageInfo) Set(val *EntitiesItemImageInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitiesItemImageInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitiesItemImageInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitiesItemImageInfo(val *EntitiesItemImageInfo) *NullableEntitiesItemImageInfo {
	return &NullableEntitiesItemImageInfo{value: val, isSet: true}
}

func (v NullableEntitiesItemImageInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitiesItemImageInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


