/*
Emby Server REST API (BETA)

Explore the Emby Server API

API version: 4.9.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package embyclient

import (
	"encoding/json"
)

// checks if the VideoCodecBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoCodecBase{}

// VideoCodecBase struct for VideoCodecBase
type VideoCodecBase struct {
	CodecDeviceInfo *CommonInterfacesICodecDeviceInfo `json:"CodecDeviceInfo,omitempty"`
	CodecKind *CodecKinds `json:"CodecKind,omitempty"`
	MediaTypeName *string `json:"MediaTypeName,omitempty"`
	VideoMediaType *VideoMediaTypes `json:"VideoMediaType,omitempty"`
	MinWidth NullableInt32 `json:"MinWidth,omitempty"`
	MaxWidth NullableInt32 `json:"MaxWidth,omitempty"`
	MinHeight NullableInt32 `json:"MinHeight,omitempty"`
	MaxHeight NullableInt32 `json:"MaxHeight,omitempty"`
	WidthAlignment NullableInt32 `json:"WidthAlignment,omitempty"`
	HeightAlignment NullableInt32 `json:"HeightAlignment,omitempty"`
	MaxBitRate *BitRate `json:"MaxBitRate,omitempty"`
	SupportedColorFormats []ColorFormats `json:"SupportedColorFormats,omitempty"`
	SupportedColorFormatStrings []string `json:"SupportedColorFormatStrings,omitempty"`
	ProfileAndLevelInformation []ProfileLevelInformation `json:"ProfileAndLevelInformation,omitempty"`
	Id *string `json:"Id,omitempty"`
	Direction *CodecDirections `json:"Direction,omitempty"`
	Name *string `json:"Name,omitempty"`
	Description *string `json:"Description,omitempty"`
	FrameworkCodec *string `json:"FrameworkCodec,omitempty"`
	IsHardwareCodec *bool `json:"IsHardwareCodec,omitempty"`
	SecondaryFramework *SecondaryFrameworks `json:"SecondaryFramework,omitempty"`
	SecondaryFrameworkCodec *string `json:"SecondaryFrameworkCodec,omitempty"`
	MaxInstanceCount NullableInt32 `json:"MaxInstanceCount,omitempty"`
	IsEnabledByDefault *bool `json:"IsEnabledByDefault,omitempty"`
	DefaultPriority *int32 `json:"DefaultPriority,omitempty"`
}

// NewVideoCodecBase instantiates a new VideoCodecBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoCodecBase() *VideoCodecBase {
	this := VideoCodecBase{}
	return &this
}

// NewVideoCodecBaseWithDefaults instantiates a new VideoCodecBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoCodecBaseWithDefaults() *VideoCodecBase {
	this := VideoCodecBase{}
	return &this
}

// GetCodecDeviceInfo returns the CodecDeviceInfo field value if set, zero value otherwise.
func (o *VideoCodecBase) GetCodecDeviceInfo() CommonInterfacesICodecDeviceInfo {
	if o == nil || IsNil(o.CodecDeviceInfo) {
		var ret CommonInterfacesICodecDeviceInfo
		return ret
	}
	return *o.CodecDeviceInfo
}

// GetCodecDeviceInfoOk returns a tuple with the CodecDeviceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetCodecDeviceInfoOk() (*CommonInterfacesICodecDeviceInfo, bool) {
	if o == nil || IsNil(o.CodecDeviceInfo) {
		return nil, false
	}
	return o.CodecDeviceInfo, true
}

// HasCodecDeviceInfo returns a boolean if a field has been set.
func (o *VideoCodecBase) HasCodecDeviceInfo() bool {
	if o != nil && !IsNil(o.CodecDeviceInfo) {
		return true
	}

	return false
}

// SetCodecDeviceInfo gets a reference to the given CommonInterfacesICodecDeviceInfo and assigns it to the CodecDeviceInfo field.
func (o *VideoCodecBase) SetCodecDeviceInfo(v CommonInterfacesICodecDeviceInfo) {
	o.CodecDeviceInfo = &v
}

// GetCodecKind returns the CodecKind field value if set, zero value otherwise.
func (o *VideoCodecBase) GetCodecKind() CodecKinds {
	if o == nil || IsNil(o.CodecKind) {
		var ret CodecKinds
		return ret
	}
	return *o.CodecKind
}

// GetCodecKindOk returns a tuple with the CodecKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetCodecKindOk() (*CodecKinds, bool) {
	if o == nil || IsNil(o.CodecKind) {
		return nil, false
	}
	return o.CodecKind, true
}

// HasCodecKind returns a boolean if a field has been set.
func (o *VideoCodecBase) HasCodecKind() bool {
	if o != nil && !IsNil(o.CodecKind) {
		return true
	}

	return false
}

// SetCodecKind gets a reference to the given CodecKinds and assigns it to the CodecKind field.
func (o *VideoCodecBase) SetCodecKind(v CodecKinds) {
	o.CodecKind = &v
}

// GetMediaTypeName returns the MediaTypeName field value if set, zero value otherwise.
func (o *VideoCodecBase) GetMediaTypeName() string {
	if o == nil || IsNil(o.MediaTypeName) {
		var ret string
		return ret
	}
	return *o.MediaTypeName
}

// GetMediaTypeNameOk returns a tuple with the MediaTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetMediaTypeNameOk() (*string, bool) {
	if o == nil || IsNil(o.MediaTypeName) {
		return nil, false
	}
	return o.MediaTypeName, true
}

// HasMediaTypeName returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMediaTypeName() bool {
	if o != nil && !IsNil(o.MediaTypeName) {
		return true
	}

	return false
}

// SetMediaTypeName gets a reference to the given string and assigns it to the MediaTypeName field.
func (o *VideoCodecBase) SetMediaTypeName(v string) {
	o.MediaTypeName = &v
}

// GetVideoMediaType returns the VideoMediaType field value if set, zero value otherwise.
func (o *VideoCodecBase) GetVideoMediaType() VideoMediaTypes {
	if o == nil || IsNil(o.VideoMediaType) {
		var ret VideoMediaTypes
		return ret
	}
	return *o.VideoMediaType
}

// GetVideoMediaTypeOk returns a tuple with the VideoMediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetVideoMediaTypeOk() (*VideoMediaTypes, bool) {
	if o == nil || IsNil(o.VideoMediaType) {
		return nil, false
	}
	return o.VideoMediaType, true
}

// HasVideoMediaType returns a boolean if a field has been set.
func (o *VideoCodecBase) HasVideoMediaType() bool {
	if o != nil && !IsNil(o.VideoMediaType) {
		return true
	}

	return false
}

// SetVideoMediaType gets a reference to the given VideoMediaTypes and assigns it to the VideoMediaType field.
func (o *VideoCodecBase) SetVideoMediaType(v VideoMediaTypes) {
	o.VideoMediaType = &v
}

// GetMinWidth returns the MinWidth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetMinWidth() int32 {
	if o == nil || IsNil(o.MinWidth.Get()) {
		var ret int32
		return ret
	}
	return *o.MinWidth.Get()
}

// GetMinWidthOk returns a tuple with the MinWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetMinWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinWidth.Get(), o.MinWidth.IsSet()
}

// HasMinWidth returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMinWidth() bool {
	if o != nil && o.MinWidth.IsSet() {
		return true
	}

	return false
}

// SetMinWidth gets a reference to the given NullableInt32 and assigns it to the MinWidth field.
func (o *VideoCodecBase) SetMinWidth(v int32) {
	o.MinWidth.Set(&v)
}
// SetMinWidthNil sets the value for MinWidth to be an explicit nil
func (o *VideoCodecBase) SetMinWidthNil() {
	o.MinWidth.Set(nil)
}

// UnsetMinWidth ensures that no value is present for MinWidth, not even an explicit nil
func (o *VideoCodecBase) UnsetMinWidth() {
	o.MinWidth.Unset()
}

// GetMaxWidth returns the MaxWidth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetMaxWidth() int32 {
	if o == nil || IsNil(o.MaxWidth.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxWidth.Get()
}

// GetMaxWidthOk returns a tuple with the MaxWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetMaxWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxWidth.Get(), o.MaxWidth.IsSet()
}

// HasMaxWidth returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMaxWidth() bool {
	if o != nil && o.MaxWidth.IsSet() {
		return true
	}

	return false
}

// SetMaxWidth gets a reference to the given NullableInt32 and assigns it to the MaxWidth field.
func (o *VideoCodecBase) SetMaxWidth(v int32) {
	o.MaxWidth.Set(&v)
}
// SetMaxWidthNil sets the value for MaxWidth to be an explicit nil
func (o *VideoCodecBase) SetMaxWidthNil() {
	o.MaxWidth.Set(nil)
}

// UnsetMaxWidth ensures that no value is present for MaxWidth, not even an explicit nil
func (o *VideoCodecBase) UnsetMaxWidth() {
	o.MaxWidth.Unset()
}

// GetMinHeight returns the MinHeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetMinHeight() int32 {
	if o == nil || IsNil(o.MinHeight.Get()) {
		var ret int32
		return ret
	}
	return *o.MinHeight.Get()
}

// GetMinHeightOk returns a tuple with the MinHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetMinHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinHeight.Get(), o.MinHeight.IsSet()
}

// HasMinHeight returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMinHeight() bool {
	if o != nil && o.MinHeight.IsSet() {
		return true
	}

	return false
}

// SetMinHeight gets a reference to the given NullableInt32 and assigns it to the MinHeight field.
func (o *VideoCodecBase) SetMinHeight(v int32) {
	o.MinHeight.Set(&v)
}
// SetMinHeightNil sets the value for MinHeight to be an explicit nil
func (o *VideoCodecBase) SetMinHeightNil() {
	o.MinHeight.Set(nil)
}

// UnsetMinHeight ensures that no value is present for MinHeight, not even an explicit nil
func (o *VideoCodecBase) UnsetMinHeight() {
	o.MinHeight.Unset()
}

// GetMaxHeight returns the MaxHeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetMaxHeight() int32 {
	if o == nil || IsNil(o.MaxHeight.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxHeight.Get()
}

// GetMaxHeightOk returns a tuple with the MaxHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetMaxHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxHeight.Get(), o.MaxHeight.IsSet()
}

// HasMaxHeight returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMaxHeight() bool {
	if o != nil && o.MaxHeight.IsSet() {
		return true
	}

	return false
}

// SetMaxHeight gets a reference to the given NullableInt32 and assigns it to the MaxHeight field.
func (o *VideoCodecBase) SetMaxHeight(v int32) {
	o.MaxHeight.Set(&v)
}
// SetMaxHeightNil sets the value for MaxHeight to be an explicit nil
func (o *VideoCodecBase) SetMaxHeightNil() {
	o.MaxHeight.Set(nil)
}

// UnsetMaxHeight ensures that no value is present for MaxHeight, not even an explicit nil
func (o *VideoCodecBase) UnsetMaxHeight() {
	o.MaxHeight.Unset()
}

// GetWidthAlignment returns the WidthAlignment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetWidthAlignment() int32 {
	if o == nil || IsNil(o.WidthAlignment.Get()) {
		var ret int32
		return ret
	}
	return *o.WidthAlignment.Get()
}

// GetWidthAlignmentOk returns a tuple with the WidthAlignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetWidthAlignmentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WidthAlignment.Get(), o.WidthAlignment.IsSet()
}

// HasWidthAlignment returns a boolean if a field has been set.
func (o *VideoCodecBase) HasWidthAlignment() bool {
	if o != nil && o.WidthAlignment.IsSet() {
		return true
	}

	return false
}

// SetWidthAlignment gets a reference to the given NullableInt32 and assigns it to the WidthAlignment field.
func (o *VideoCodecBase) SetWidthAlignment(v int32) {
	o.WidthAlignment.Set(&v)
}
// SetWidthAlignmentNil sets the value for WidthAlignment to be an explicit nil
func (o *VideoCodecBase) SetWidthAlignmentNil() {
	o.WidthAlignment.Set(nil)
}

// UnsetWidthAlignment ensures that no value is present for WidthAlignment, not even an explicit nil
func (o *VideoCodecBase) UnsetWidthAlignment() {
	o.WidthAlignment.Unset()
}

// GetHeightAlignment returns the HeightAlignment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetHeightAlignment() int32 {
	if o == nil || IsNil(o.HeightAlignment.Get()) {
		var ret int32
		return ret
	}
	return *o.HeightAlignment.Get()
}

// GetHeightAlignmentOk returns a tuple with the HeightAlignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetHeightAlignmentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HeightAlignment.Get(), o.HeightAlignment.IsSet()
}

// HasHeightAlignment returns a boolean if a field has been set.
func (o *VideoCodecBase) HasHeightAlignment() bool {
	if o != nil && o.HeightAlignment.IsSet() {
		return true
	}

	return false
}

// SetHeightAlignment gets a reference to the given NullableInt32 and assigns it to the HeightAlignment field.
func (o *VideoCodecBase) SetHeightAlignment(v int32) {
	o.HeightAlignment.Set(&v)
}
// SetHeightAlignmentNil sets the value for HeightAlignment to be an explicit nil
func (o *VideoCodecBase) SetHeightAlignmentNil() {
	o.HeightAlignment.Set(nil)
}

// UnsetHeightAlignment ensures that no value is present for HeightAlignment, not even an explicit nil
func (o *VideoCodecBase) UnsetHeightAlignment() {
	o.HeightAlignment.Unset()
}

// GetMaxBitRate returns the MaxBitRate field value if set, zero value otherwise.
func (o *VideoCodecBase) GetMaxBitRate() BitRate {
	if o == nil || IsNil(o.MaxBitRate) {
		var ret BitRate
		return ret
	}
	return *o.MaxBitRate
}

// GetMaxBitRateOk returns a tuple with the MaxBitRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetMaxBitRateOk() (*BitRate, bool) {
	if o == nil || IsNil(o.MaxBitRate) {
		return nil, false
	}
	return o.MaxBitRate, true
}

// HasMaxBitRate returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMaxBitRate() bool {
	if o != nil && !IsNil(o.MaxBitRate) {
		return true
	}

	return false
}

// SetMaxBitRate gets a reference to the given BitRate and assigns it to the MaxBitRate field.
func (o *VideoCodecBase) SetMaxBitRate(v BitRate) {
	o.MaxBitRate = &v
}

// GetSupportedColorFormats returns the SupportedColorFormats field value if set, zero value otherwise.
func (o *VideoCodecBase) GetSupportedColorFormats() []ColorFormats {
	if o == nil || IsNil(o.SupportedColorFormats) {
		var ret []ColorFormats
		return ret
	}
	return o.SupportedColorFormats
}

// GetSupportedColorFormatsOk returns a tuple with the SupportedColorFormats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetSupportedColorFormatsOk() ([]ColorFormats, bool) {
	if o == nil || IsNil(o.SupportedColorFormats) {
		return nil, false
	}
	return o.SupportedColorFormats, true
}

// HasSupportedColorFormats returns a boolean if a field has been set.
func (o *VideoCodecBase) HasSupportedColorFormats() bool {
	if o != nil && !IsNil(o.SupportedColorFormats) {
		return true
	}

	return false
}

// SetSupportedColorFormats gets a reference to the given []ColorFormats and assigns it to the SupportedColorFormats field.
func (o *VideoCodecBase) SetSupportedColorFormats(v []ColorFormats) {
	o.SupportedColorFormats = v
}

// GetSupportedColorFormatStrings returns the SupportedColorFormatStrings field value if set, zero value otherwise.
func (o *VideoCodecBase) GetSupportedColorFormatStrings() []string {
	if o == nil || IsNil(o.SupportedColorFormatStrings) {
		var ret []string
		return ret
	}
	return o.SupportedColorFormatStrings
}

// GetSupportedColorFormatStringsOk returns a tuple with the SupportedColorFormatStrings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetSupportedColorFormatStringsOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedColorFormatStrings) {
		return nil, false
	}
	return o.SupportedColorFormatStrings, true
}

// HasSupportedColorFormatStrings returns a boolean if a field has been set.
func (o *VideoCodecBase) HasSupportedColorFormatStrings() bool {
	if o != nil && !IsNil(o.SupportedColorFormatStrings) {
		return true
	}

	return false
}

// SetSupportedColorFormatStrings gets a reference to the given []string and assigns it to the SupportedColorFormatStrings field.
func (o *VideoCodecBase) SetSupportedColorFormatStrings(v []string) {
	o.SupportedColorFormatStrings = v
}

// GetProfileAndLevelInformation returns the ProfileAndLevelInformation field value if set, zero value otherwise.
func (o *VideoCodecBase) GetProfileAndLevelInformation() []ProfileLevelInformation {
	if o == nil || IsNil(o.ProfileAndLevelInformation) {
		var ret []ProfileLevelInformation
		return ret
	}
	return o.ProfileAndLevelInformation
}

// GetProfileAndLevelInformationOk returns a tuple with the ProfileAndLevelInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetProfileAndLevelInformationOk() ([]ProfileLevelInformation, bool) {
	if o == nil || IsNil(o.ProfileAndLevelInformation) {
		return nil, false
	}
	return o.ProfileAndLevelInformation, true
}

// HasProfileAndLevelInformation returns a boolean if a field has been set.
func (o *VideoCodecBase) HasProfileAndLevelInformation() bool {
	if o != nil && !IsNil(o.ProfileAndLevelInformation) {
		return true
	}

	return false
}

// SetProfileAndLevelInformation gets a reference to the given []ProfileLevelInformation and assigns it to the ProfileAndLevelInformation field.
func (o *VideoCodecBase) SetProfileAndLevelInformation(v []ProfileLevelInformation) {
	o.ProfileAndLevelInformation = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VideoCodecBase) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VideoCodecBase) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VideoCodecBase) SetId(v string) {
	o.Id = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *VideoCodecBase) GetDirection() CodecDirections {
	if o == nil || IsNil(o.Direction) {
		var ret CodecDirections
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetDirectionOk() (*CodecDirections, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *VideoCodecBase) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given CodecDirections and assigns it to the Direction field.
func (o *VideoCodecBase) SetDirection(v CodecDirections) {
	o.Direction = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VideoCodecBase) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VideoCodecBase) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VideoCodecBase) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *VideoCodecBase) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *VideoCodecBase) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *VideoCodecBase) SetDescription(v string) {
	o.Description = &v
}

// GetFrameworkCodec returns the FrameworkCodec field value if set, zero value otherwise.
func (o *VideoCodecBase) GetFrameworkCodec() string {
	if o == nil || IsNil(o.FrameworkCodec) {
		var ret string
		return ret
	}
	return *o.FrameworkCodec
}

// GetFrameworkCodecOk returns a tuple with the FrameworkCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetFrameworkCodecOk() (*string, bool) {
	if o == nil || IsNil(o.FrameworkCodec) {
		return nil, false
	}
	return o.FrameworkCodec, true
}

// HasFrameworkCodec returns a boolean if a field has been set.
func (o *VideoCodecBase) HasFrameworkCodec() bool {
	if o != nil && !IsNil(o.FrameworkCodec) {
		return true
	}

	return false
}

// SetFrameworkCodec gets a reference to the given string and assigns it to the FrameworkCodec field.
func (o *VideoCodecBase) SetFrameworkCodec(v string) {
	o.FrameworkCodec = &v
}

// GetIsHardwareCodec returns the IsHardwareCodec field value if set, zero value otherwise.
func (o *VideoCodecBase) GetIsHardwareCodec() bool {
	if o == nil || IsNil(o.IsHardwareCodec) {
		var ret bool
		return ret
	}
	return *o.IsHardwareCodec
}

// GetIsHardwareCodecOk returns a tuple with the IsHardwareCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetIsHardwareCodecOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHardwareCodec) {
		return nil, false
	}
	return o.IsHardwareCodec, true
}

// HasIsHardwareCodec returns a boolean if a field has been set.
func (o *VideoCodecBase) HasIsHardwareCodec() bool {
	if o != nil && !IsNil(o.IsHardwareCodec) {
		return true
	}

	return false
}

// SetIsHardwareCodec gets a reference to the given bool and assigns it to the IsHardwareCodec field.
func (o *VideoCodecBase) SetIsHardwareCodec(v bool) {
	o.IsHardwareCodec = &v
}

// GetSecondaryFramework returns the SecondaryFramework field value if set, zero value otherwise.
func (o *VideoCodecBase) GetSecondaryFramework() SecondaryFrameworks {
	if o == nil || IsNil(o.SecondaryFramework) {
		var ret SecondaryFrameworks
		return ret
	}
	return *o.SecondaryFramework
}

// GetSecondaryFrameworkOk returns a tuple with the SecondaryFramework field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetSecondaryFrameworkOk() (*SecondaryFrameworks, bool) {
	if o == nil || IsNil(o.SecondaryFramework) {
		return nil, false
	}
	return o.SecondaryFramework, true
}

// HasSecondaryFramework returns a boolean if a field has been set.
func (o *VideoCodecBase) HasSecondaryFramework() bool {
	if o != nil && !IsNil(o.SecondaryFramework) {
		return true
	}

	return false
}

// SetSecondaryFramework gets a reference to the given SecondaryFrameworks and assigns it to the SecondaryFramework field.
func (o *VideoCodecBase) SetSecondaryFramework(v SecondaryFrameworks) {
	o.SecondaryFramework = &v
}

// GetSecondaryFrameworkCodec returns the SecondaryFrameworkCodec field value if set, zero value otherwise.
func (o *VideoCodecBase) GetSecondaryFrameworkCodec() string {
	if o == nil || IsNil(o.SecondaryFrameworkCodec) {
		var ret string
		return ret
	}
	return *o.SecondaryFrameworkCodec
}

// GetSecondaryFrameworkCodecOk returns a tuple with the SecondaryFrameworkCodec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetSecondaryFrameworkCodecOk() (*string, bool) {
	if o == nil || IsNil(o.SecondaryFrameworkCodec) {
		return nil, false
	}
	return o.SecondaryFrameworkCodec, true
}

// HasSecondaryFrameworkCodec returns a boolean if a field has been set.
func (o *VideoCodecBase) HasSecondaryFrameworkCodec() bool {
	if o != nil && !IsNil(o.SecondaryFrameworkCodec) {
		return true
	}

	return false
}

// SetSecondaryFrameworkCodec gets a reference to the given string and assigns it to the SecondaryFrameworkCodec field.
func (o *VideoCodecBase) SetSecondaryFrameworkCodec(v string) {
	o.SecondaryFrameworkCodec = &v
}

// GetMaxInstanceCount returns the MaxInstanceCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoCodecBase) GetMaxInstanceCount() int32 {
	if o == nil || IsNil(o.MaxInstanceCount.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxInstanceCount.Get()
}

// GetMaxInstanceCountOk returns a tuple with the MaxInstanceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoCodecBase) GetMaxInstanceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxInstanceCount.Get(), o.MaxInstanceCount.IsSet()
}

// HasMaxInstanceCount returns a boolean if a field has been set.
func (o *VideoCodecBase) HasMaxInstanceCount() bool {
	if o != nil && o.MaxInstanceCount.IsSet() {
		return true
	}

	return false
}

// SetMaxInstanceCount gets a reference to the given NullableInt32 and assigns it to the MaxInstanceCount field.
func (o *VideoCodecBase) SetMaxInstanceCount(v int32) {
	o.MaxInstanceCount.Set(&v)
}
// SetMaxInstanceCountNil sets the value for MaxInstanceCount to be an explicit nil
func (o *VideoCodecBase) SetMaxInstanceCountNil() {
	o.MaxInstanceCount.Set(nil)
}

// UnsetMaxInstanceCount ensures that no value is present for MaxInstanceCount, not even an explicit nil
func (o *VideoCodecBase) UnsetMaxInstanceCount() {
	o.MaxInstanceCount.Unset()
}

// GetIsEnabledByDefault returns the IsEnabledByDefault field value if set, zero value otherwise.
func (o *VideoCodecBase) GetIsEnabledByDefault() bool {
	if o == nil || IsNil(o.IsEnabledByDefault) {
		var ret bool
		return ret
	}
	return *o.IsEnabledByDefault
}

// GetIsEnabledByDefaultOk returns a tuple with the IsEnabledByDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetIsEnabledByDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabledByDefault) {
		return nil, false
	}
	return o.IsEnabledByDefault, true
}

// HasIsEnabledByDefault returns a boolean if a field has been set.
func (o *VideoCodecBase) HasIsEnabledByDefault() bool {
	if o != nil && !IsNil(o.IsEnabledByDefault) {
		return true
	}

	return false
}

// SetIsEnabledByDefault gets a reference to the given bool and assigns it to the IsEnabledByDefault field.
func (o *VideoCodecBase) SetIsEnabledByDefault(v bool) {
	o.IsEnabledByDefault = &v
}

// GetDefaultPriority returns the DefaultPriority field value if set, zero value otherwise.
func (o *VideoCodecBase) GetDefaultPriority() int32 {
	if o == nil || IsNil(o.DefaultPriority) {
		var ret int32
		return ret
	}
	return *o.DefaultPriority
}

// GetDefaultPriorityOk returns a tuple with the DefaultPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCodecBase) GetDefaultPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultPriority) {
		return nil, false
	}
	return o.DefaultPriority, true
}

// HasDefaultPriority returns a boolean if a field has been set.
func (o *VideoCodecBase) HasDefaultPriority() bool {
	if o != nil && !IsNil(o.DefaultPriority) {
		return true
	}

	return false
}

// SetDefaultPriority gets a reference to the given int32 and assigns it to the DefaultPriority field.
func (o *VideoCodecBase) SetDefaultPriority(v int32) {
	o.DefaultPriority = &v
}

func (o VideoCodecBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoCodecBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CodecDeviceInfo) {
		toSerialize["CodecDeviceInfo"] = o.CodecDeviceInfo
	}
	if !IsNil(o.CodecKind) {
		toSerialize["CodecKind"] = o.CodecKind
	}
	if !IsNil(o.MediaTypeName) {
		toSerialize["MediaTypeName"] = o.MediaTypeName
	}
	if !IsNil(o.VideoMediaType) {
		toSerialize["VideoMediaType"] = o.VideoMediaType
	}
	if o.MinWidth.IsSet() {
		toSerialize["MinWidth"] = o.MinWidth.Get()
	}
	if o.MaxWidth.IsSet() {
		toSerialize["MaxWidth"] = o.MaxWidth.Get()
	}
	if o.MinHeight.IsSet() {
		toSerialize["MinHeight"] = o.MinHeight.Get()
	}
	if o.MaxHeight.IsSet() {
		toSerialize["MaxHeight"] = o.MaxHeight.Get()
	}
	if o.WidthAlignment.IsSet() {
		toSerialize["WidthAlignment"] = o.WidthAlignment.Get()
	}
	if o.HeightAlignment.IsSet() {
		toSerialize["HeightAlignment"] = o.HeightAlignment.Get()
	}
	if !IsNil(o.MaxBitRate) {
		toSerialize["MaxBitRate"] = o.MaxBitRate
	}
	if !IsNil(o.SupportedColorFormats) {
		toSerialize["SupportedColorFormats"] = o.SupportedColorFormats
	}
	if !IsNil(o.SupportedColorFormatStrings) {
		toSerialize["SupportedColorFormatStrings"] = o.SupportedColorFormatStrings
	}
	if !IsNil(o.ProfileAndLevelInformation) {
		toSerialize["ProfileAndLevelInformation"] = o.ProfileAndLevelInformation
	}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Direction) {
		toSerialize["Direction"] = o.Direction
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.FrameworkCodec) {
		toSerialize["FrameworkCodec"] = o.FrameworkCodec
	}
	if !IsNil(o.IsHardwareCodec) {
		toSerialize["IsHardwareCodec"] = o.IsHardwareCodec
	}
	if !IsNil(o.SecondaryFramework) {
		toSerialize["SecondaryFramework"] = o.SecondaryFramework
	}
	if !IsNil(o.SecondaryFrameworkCodec) {
		toSerialize["SecondaryFrameworkCodec"] = o.SecondaryFrameworkCodec
	}
	if o.MaxInstanceCount.IsSet() {
		toSerialize["MaxInstanceCount"] = o.MaxInstanceCount.Get()
	}
	if !IsNil(o.IsEnabledByDefault) {
		toSerialize["IsEnabledByDefault"] = o.IsEnabledByDefault
	}
	if !IsNil(o.DefaultPriority) {
		toSerialize["DefaultPriority"] = o.DefaultPriority
	}
	return toSerialize, nil
}

type NullableVideoCodecBase struct {
	value *VideoCodecBase
	isSet bool
}

func (v NullableVideoCodecBase) Get() *VideoCodecBase {
	return v.value
}

func (v *NullableVideoCodecBase) Set(val *VideoCodecBase) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoCodecBase) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoCodecBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoCodecBase(val *VideoCodecBase) *NullableVideoCodecBase {
	return &NullableVideoCodecBase{value: val, isSet: true}
}

func (v NullableVideoCodecBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoCodecBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


