// Copyright (c) HashiCorp, Inc.

/*
Emby Server REST API (BETA)

Testing ItemUpdateServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package embyclient

import (
	"context"
	openapiclient "github.com/Kamaroth92/terraform-provider-emby/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_embyclient_ItemUpdateServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ItemUpdateServiceAPIService GetItemsByItemidMetadataeditor", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var itemId string

		resp, httpRes, err := apiClient.ItemUpdateServiceAPI.GetItemsByItemidMetadataeditor(context.Background(), itemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemUpdateServiceAPIService PostItemsByItemid", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var itemId string

		httpRes, err := apiClient.ItemUpdateServiceAPI.PostItemsByItemid(context.Background(), itemId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
